/* ============================================================
 *  PAC 自动代理配置 —— 国内直连，海外走代理
 *  地址：https://proxy.i-xx.top/proxy.pac
 *  代理：192.168.31.161:7890
 * ------------------------------------------------------------
 *  匹配顺序：
 *    1. 本机 / 局域网地址（localhost、无点主机名、127.x、10.x、
 *       172.16-31.x、192.168.x、169.254.x、0.x、*.local/*.lan/
 *       *.home/*.internal/*.i-xx.top）      → DIRECT
 *    2. 纯 IP 访问（内网直连；公网 IP 也直连，见文末说明）→ DIRECT
 *    3. 国内域名（下表 + 国内顶级域）        → DIRECT
 *    4. 其余域名（含全部海外站点）           → PROXY 192.168.31.161:7890
 *    代理不可用时回退 DIRECT，离开该局域网仍可上网。
 * ============================================================ */

var PROXY_ADDR = "192.168.31.161:7890";
var PROXY_RULE = "PROXY " + PROXY_ADDR;
var FALLBACK   = PROXY_RULE + "; DIRECT";

/* ------------------------------------------------------------
 * 国内域名表
 * 来源：Loyalsoldier/v2ray-rules-dat 的 direct-list.txt（增强版）
 *       （约 11 万条，比原 dnsmasq-china-list 多 700+ 条）
 * 本表取其中被全球访问量前 100 万域名清单（Cisco Umbrella top-1m）
 * 真实命中的条目，共 4466 条，另人工补充少量常用域名。
 * 生成日期：2026-09-22
 * ------------------------------------------------------------ */
var CN_DOMAINS =
"007swz.com\n" +
"010zaixian.com\n" +
"027art.com\n" +
"03k.org\n" +
"0550.com\n" +
"0594.com\n" +
"0kkkkkt.com\n" +
"10010.com\n" +
"100nets.com\n" +
"100ppi.com\n" +
"100tal.com\n" +
"100xuexi.com\n" +
"100ycdn.com\n" +
"101.com\n" +
"1010jiajiao.com\n" +
"101weiqi.com\n" +
"1024tools.com\n" +
"1073.com\n" +
"10moons.com\n" +
"110.com\n" +
"110ask.com\n" +
"11315.com\n" +
"11467.com\n" +
"114chn.com\n" +
"114dns.com\n" +
"114ic.com\n" +
"114piaowu.com\n" +
"115.com\n" +
"118114.net\n" +
"120ask.com\n" +
"120x.net\n" +
"1233dns.com\n" +
"12365auto.com\n" +
"123clouddisk.com\n" +
"123clouddrive.net\n" +
"123pan.com\n" +
"123ths.com\n" +
"123xueshu.com\n" +
"126.com\n" +
"126.net\n" +
"127.net\n" +
"135editor.com\n" +
"1360.com\n" +
"136bet.app\n" +
"139.com\n" +
"13yx.com\n" +
"15166.com\n" +
"160.com\n" +
"163.com\n" +
"163.net\n" +
"163img.com\n" +
"163jiasu.com\n" +
"163yun.com\n" +
"166.com\n" +
"166.net\n" +
"166cdn.com\n" +
"168.com\n" +
"1688.com\n" +
"16888.com\n" +
"17173.com\n" +
"17173cdn.com\n" +
"178.com\n" +
"178448.com\n" +
"17ex.com\n" +
"17kxgame.com\n" +
"17tcw.com\n" +
"17track.net\n" +
"17usoft.com\n" +
"17win.com\n" +
"17zwd.com\n" +
"18183.com\n" +
"182682.xyz\n" +
"188.com\n" +
"189cube.com\n" +
"189smarthome.com\n" +
"1905.com\n" +
"199u2.com\n" +
"19lou.com\n" +
"1b1tech.com\n" +
"1kic.com\n" +
"1mpi.com\n" +
"1qianbao.com\n" +
"1rtb.com\n" +
"1rtb.net\n" +
"1sapp.com\n" +
"1ting.com\n" +
"20130123.com\n" +
"2023game.com\n" +
"21-sun.com\n" +
"21cn.com\n" +
"21cn.net\n" +
"21cnjy.com\n" +
"21ic.com\n" +
"21jingji.com\n" +
"21na.com\n" +
"2288.org\n" +
"233.com\n" +
"233leyuan.com\n" +
"2345.cc\n" +
"2345.com\n" +
"2345cdn.net\n" +
"23du.com\n" +
"23img.com\n" +
"258fuwu.com\n" +
"25pp.com\n" +
"263.net\n" +
"263xmail.com\n" +
"265.com\n" +
"2980.com\n" +
"2loveyou.com\n" +
"2q10.com\n" +
"300624.com\n" +
"300hu.com\n" +
"31gamestudio.com\n" +
"321fenx.com\n" +
"3322.net\n" +
"3322.org\n" +
"35.com\n" +
"35.net\n" +
"35go.net\n" +
"360-g.net\n" +
"360-game.net\n" +
"360.com\n" +
"3600.com\n" +
"360anyu.com\n" +
"360buy.com\n" +
"360buyimg.com\n" +
"360che.com\n" +
"360cloudwaf.com\n" +
"360doc.com\n" +
"360in.com\n" +
"360kan.com\n" +
"360kuai.com\n" +
"360os.com\n" +
"360panyun.com\n" +
"360qhcdn.com\n" +
"360safe.com\n" +
"360simg.com\n" +
"360sres.com\n" +
"360totalsecurity.com\n" +
"360tpcdn.com\n" +
"360tres.com\n" +
"360wzws.com\n" +
"3618med.com\n" +
"361sport.com\n" +
"365dmp.com\n" +
"365yg.com\n" +
"36hjob.com\n" +
"36kr.com\n" +
"36krcdn.com\n" +
"37.com\n" +
"37wan.com\n" +
"38hot.net\n" +
"39.net\n" +
"3conline.com\n" +
"3d66.com\n" +
"3dmgame.com\n" +
"3fang.com\n" +
"3gmimo.com\n" +
"3u.com\n" +
"4008000000.com\n" +
"400qikan.com\n" +
"4399.com\n" +
"4399api.net\n" +
"4399sy.com\n" +
"4everdns.com\n" +
"4px.com\n" +
"500.com\n" +
"5054399.com\n" +
"508sys.com\n" +
"50bangzh.com\n" +
"50union.com\n" +
"51.com\n" +
"51.la\n" +
"5118.com\n" +
"5120.com\n" +
"51969.com\n" +
"51changdu.com\n" +
"51cto.com\n" +
"51daifu.com\n" +
"51dzw.com\n" +
"51fanli.net\n" +
"51fytx.com\n" +
"51jiaoxi.com\n" +
"51job.com\n" +
"51jobapp.com\n" +
"51jobcdn.com\n" +
"51jobdns.com\n" +
"51microshop.com\n" +
"51papers.com\n" +
"51sanhu.com\n" +
"51sole.com\n" +
"51talk.com\n" +
"51touch.com\n" +
"51tyty.com\n" +
"51vip.biz\n" +
"51wendang.com\n" +
"51wnl-cq.com\n" +
"51wnl.com\n" +
"51y5.net\n" +
"51yidun.com\n" +
"51yund.com\n" +
"51zsjc.com\n" +
"520yidui.com\n" +
"5211game.com\n" +
"52pcfree.com\n" +
"52pk.com\n" +
"52qumao.com\n" +
"52songshu.com\n" +
"52tt.com\n" +
"52wmb.com\n" +
"52yyxk.com\n" +
"53iq.com\n" +
"53kf.com\n" +
"56.com\n" +
"56tvc.com\n" +
"58.com\n" +
"588ku.com\n" +
"58che.com\n" +
"58iclick.com\n" +
"58pic.com\n" +
"5ddd.com\n" +
"5dmail.net\n" +
"5eplay.com\n" +
"5eplaycdn.com\n" +
"5i5j.com\n" +
"5idhl.com\n" +
"5ifund.com\n" +
"5isohu.com\n" +
"5jli.com\n" +
"5read.com\n" +
"6-china.com\n" +
"616pic.com\n" +
"63cj.com\n" +
"64365.com\n" +
"6655.la\n" +
"66mobi.com\n" +
"699pic.com\n" +
"6fast.com\n" +
"6huo.com\n" +
"6my575.com\n" +
"6wtx.com\n" +
"70jj.com\n" +
"71360.com\n" +
"71e.com\n" +
"71edge.com\n" +
"720yun.com\n" +
"72dns.com\n" +
"72dns.net\n" +
"72la.com\n" +
"788v.com\n" +
"78dm.net\n" +
"7cname.com\n" +
"7fresh.com\n" +
"7moor.com\n" +
"7road.net\n" +
"800best.com\n" +
"80data.net\n" +
"81art.com\n" +
"81zhongwenx.com\n" +
"8264.com\n" +
"86office.com\n" +
"86pla.com\n" +
"876dns.com\n" +
"87g.com\n" +
"8866.org\n" +
"88cdn.com\n" +
"8bo.com\n" +
"8ziben.com\n" +
"912688.com\n" +
"9166yx.com\n" +
"91https.com\n" +
"91wan.com\n" +
"9217web.com\n" +
"93soso.com\n" +
"95021.com\n" +
"951dns.com\n" +
"95508.com\n" +
"95516.com\n" +
"99.com\n" +
"9911yx.com\n" +
"9917.com\n" +
"9966.org\n" +
"999ask.com\n" +
"99uri.com\n" +
"9liuda.com\n" +
"9wee.com\n" +
"9you.com\n" +
"a9vg.com\n" +
"abc188.com\n" +
"abcdv.net\n" +
"abchina.com\n" +
"ablesci.com\n" +
"abslw.com\n" +
"abupdate.com\n" +
"accio.com\n" +
"acobt.tech\n" +
"acs.org\n" +
"activity-wbsj.com\n" +
"ad-survey.com\n" +
"adanxing.com\n" +
"adbiding.com\n" +
"adbkwai.com\n" +
"addx.live\n" +
"adhimalayandi.com\n" +
"adinall.com\n" +
"adkwai.com\n" +
"admamax.com\n" +
"admbucket.com\n" +
"admile.xyz\n" +
"adqtt.net\n" +
"adseye.com\n" +
"adseyeservice.com\n" +
"adukwai.com\n" +
"adups.com\n" +
"adview.com\n" +
"advlion.com\n" +
"adwangmai.com\n" +
"adwanji.com\n" +
"adxvip.com\n" +
"afirstsoft.com\n" +
"aflink.com\n" +
"afunapp.com\n" +
"afzhan.com\n" +
"agconnect.link\n" +
"agora.io\n" +
"agoralab.co\n" +
"ah7907.com\n" +
"ahdohpiechei.com\n" +
"ai.cc\n" +
"aibase.com\n" +
"aicdn.com\n" +
"aicdn2.com\n" +
"aicdn5.com\n" +
"aichaoxing.com\n" +
"aiclk.com\n" +
"aiconn.com\n" +
"aidcgroup.net\n" +
"aidoczh.com\n" +
"aiegde.com\n" +
"aigei.com\n" +
"aigexing.com\n" +
"aihelp.net\n" +
"aihelpcn.net\n" +
"aihuishou.com\n" +
"ailingmao.com\n" +
"aimap.com\n" +
"aipage.com\n" +
"aippt.com\n" +
"air-matters.com\n" +
"airchina.com\n" +
"airchinacargo.com\n" +
"airstarfinance.net\n" +
"airtac.com\n" +
"aisee.tv\n" +
"aishengji.com\n" +
"aishuttler.com\n" +
"aispeech.com\n" +
"aiyituo.com\n" +
"aizhan.com\n" +
"aizhantj.com\n" +
"ajkimg.com\n" +
"ak-d.tripcdn.com\n" +
"ak-v.tripcdn.com\n" +
"aka700.net\n" +
"akadns99.net\n" +
"akamai.com\n" +
"aki-game.com\n" +
"aki-game.net\n" +
"aki-game2.com\n" +
"aki-game2.net\n" +
"akkogear.com\n" +
"alcasset.com\n" +
"algogear.com\n" +
"ali213.net\n" +
"aliapp.com\n" +
"aliapp.org\n" +
"alibaba-inc.com\n" +
"alibaba.com\n" +
"alibabachengdun.com\n" +
"alibabachengdun.net\n" +
"alibabacloud.com\n" +
"alibabacorp.com\n" +
"alibabadns.com\n" +
"alibabagroup.com\n" +
"alibabausercontent.com\n" +
"alibtrip.com\n" +
"alicdn.com\n" +
"alicloudapi.com\n" +
"alicloudwaf.com\n" +
"alicontainer.com\n" +
"alidns.com\n" +
"aliexpress-media.com\n" +
"aliexpress.com\n" +
"aliexpress.ru\n" +
"aliexpress.us\n" +
"aligames.com\n" +
"aligfwaf.com\n" +
"aliimg.com\n" +
"alikunlun.com\n" +
"alikunlun.net\n" +
"alimama.com\n" +
"alimebot.com\n" +
"alipan.com\n" +
"alipay-eco.com\n" +
"alipay.com\n" +
"alipay.hk\n" +
"alipaydns.com\n" +
"alipayobjects.com\n" +
"alipayplus.com\n" +
"aliplus.com\n" +
"alitrip.com\n" +
"alivecdn.com\n" +
"aliyun-esa.net\n" +
"aliyun-inc.com\n" +
"aliyun.com\n" +
"aliyuncs.com\n" +
"aliyuncsslb.com\n" +
"aliyuncsslbintl.com\n" +
"aliyunddos0005.com\n" +
"aliyunddos0010.com\n" +
"aliyunddos0012.com\n" +
"aliyunddos0018.com\n" +
"aliyunddos0025.com\n" +
"aliyunddos0027.com\n" +
"aliyunddos0030.com\n" +
"aliyunddos1001.com\n" +
"aliyunddos1002.com\n" +
"aliyunddos1003.com\n" +
"aliyunddos1005.com\n" +
"aliyunddos1006.com\n" +
"aliyunddos1008.com\n" +
"aliyunddos1009.com\n" +
"aliyunddos1011.com\n" +
"aliyunddos1012.com\n" +
"aliyunddos1015.com\n" +
"aliyunddos1016.com\n" +
"aliyunddos1019.com\n" +
"aliyunddos1020.com\n" +
"aliyunddos1021.com\n" +
"aliyunddos1022.com\n" +
"aliyunddos1023.com\n" +
"aliyunddos1024.com\n" +
"aliyunddos1025.com\n" +
"aliyunddos1028.com\n" +
"aliyunddos1029.com\n" +
"aliyunddos1030.com\n" +
"aliyundrive.com\n" +
"aliyundunwaf.com\n" +
"aliyunga0017.com\n" +
"aliyunga0018.com\n" +
"aliyunga0019.com\n" +
"aliyungf.com\n" +
"aliyunpds.com\n" +
"aliyunwaf.com\n" +
"aliyunwaf1.com\n" +
"aliyunwaf2.com\n" +
"aliyunwaf3.com\n" +
"aliyunwaf4.com\n" +
"aliyunwaf5.com\n" +
"allapp.link\n" +
"allawnfs.com\n" +
"allawntech.com\n" +
"allfootballapp.com\n" +
"allinpay.com\n" +
"alllook.tv\n" +
"allsaintsmusic.com\n" +
"allstatics.com\n" +
"alltuu.com\n" +
"allwinso.com\n" +
"alphassl.com\n" +
"alwindoor.com\n" +
"alyasset.com\n" +
"amap.com\n" +
"amazfit.com\n" +
"amegroups.org\n" +
"amemv.com\n" +
"amflowbikes.com\n" +
"ampmake.com\n" +
"amsoveasea.com\n" +
"amz123.com\n" +
"analog.com\n" +
"angui.org\n" +
"anictdns.click\n" +
"anictdns.store\n" +
"aniu.com\n" +
"anjuke.com\n" +
"anjukestatic.com\n" +
"ankai.com\n" +
"anker-in.com\n" +
"anlian.co\n" +
"anta.com\n" +
"antbank.hk\n" +
"antfin.com\n" +
"antgroup.com\n" +
"antibanads.com\n" +
"anticheatexpert.com\n" +
"antom.com\n" +
"antpcdn.com\n" +
"antpedia.com\n" +
"antutu.com\n" +
"anycubic.com\n" +
"anyelse.com\n" +
"anyscdn.com\n" +
"aocde.com\n" +
"aodianyun.com\n" +
"aorankj.com\n" +
"aoscdn.com\n" +
"aoshitang.com\n" +
"aoyoux.com\n" +
"apdcdn.com\n" +
"api.anythinktech.com\n" +
"apiairasia.com\n" +
"apicgate.com\n" +
"apitd.net\n" +
"apkevery.com\n" +
"apollo.auto\n" +
"app17.com\n" +
"appjiagu.com\n" +
"appletuan.com\n" +
"applogcdn.com\n" +
"applysquare.com\n" +
"appmifile.com\n" +
"appracle.com\n" +
"appsflyer-cn.com\n" +
"appsimg.com\n" +
"apptaxi.net\n" +
"apptrackerlink.com\n" +
"appvipshop.com\n" +
"apsgo.com\n" +
"aqara.com\n" +
"aqyad.com\n" +
"archiposition.com\n" +
"armvm.com\n" +
"artron.net\n" +
"asia-cdn.com\n" +
"asiadvb.net\n" +
"asiainfo-sec.com\n" +
"askci.com\n" +
"askdiandian.com\n" +
"asklink.com\n" +
"aslk2018.com\n" +
"asrmicro.com\n" +
"assrt.net\n" +
"aswetalk.net\n" +
"atianqi.com\n" +
"atk.pro\n" +
"atrustdns.com\n" +
"attribuly.com\n" +
"autodl.com\n" +
"autodnsv1.com\n" +
"autoitx.com\n" +
"autonavi.com\n" +
"auxsolcloud.com\n" +
"av380.net\n" +
"avlsec.com\n" +
"avlyun.com\n" +
"aweray.com\n" +
"awsdns-cn-10.com\n" +
"awsdns-cn-29.biz\n" +
"awsdns-cn-37.net\n" +
"awsdns-cn-40.net\n" +
"awsdns-cn-52.biz\n" +
"awsdns-cn-60.com\n" +
"awtmt.com\n" +
"b.c2r.ts.cdn.office.net\n" +
"b23.tv\n" +
"b2b.biz\n" +
"b2b168.com\n" +
"b2b168.org\n" +
"babybus.com\n" +
"babytree.com\n" +
"badambiz.com\n" +
"bahens.com\n" +
"baicai.com\n" +
"baicizhan.com\n" +
"baidu-int.com\n" +
"baidu-itm.com\n" +
"baidu.com\n" +
"baiduads.com\n" +
"baidubce.com\n" +
"baiducontent.com\n" +
"baidupcs.com\n" +
"baidustatic.com\n" +
"baihe.com\n" +
"baihemob.com\n" +
"baijiantest.com\n" +
"baijiayun.com\n" +
"baike.com\n" +
"baikevod.com\n" +
"baishan-cloud.net\n" +
"baishancloud.com\n" +
"baiwang.com\n" +
"baixing.com\n" +
"baixing.net\n" +
"baiyou100.com\n" +
"baizhanlive.com\n" +
"bakstotre.com\n" +
"baletu.com\n" +
"bambu-lab.com\n" +
"bangcle.com\n" +
"bangdao-tech.com\n" +
"banjixiaoguanjia.com\n" +
"bankcomm.com\n" +
"bankofchina.com\n" +
"banwo365.com\n" +
"baofeng.com\n" +
"baofeng.net\n" +
"baomitu.com\n" +
"baozun.com\n" +
"baydn.com\n" +
"bayescom.com\n" +
"bbk.com\n" +
"bblcdn.com\n" +
"bblmw.com\n" +
"bblops.com\n" +
"bbsls.net\n" +
"bccn.net\n" +
"bcdnx.com\n" +
"bcebos.com\n" +
"bcelive.com\n" +
"bcghotel.com\n" +
"bchlkj.com\n" +
"bczcdn.com\n" +
"bd-caict.com\n" +
"bdcgslb.com\n" +
"bdgp.cc\n" +
"bdimg.com\n" +
"bdstatic.com\n" +
"bdurl.net\n" +
"bdxiguaimg.com\n" +
"bdxiguastatic.com\n" +
"bdxiguavod.com\n" +
"bdydns.com\n" +
"bdysite.com\n" +
"beatsbydre.com\n" +
"beckwai.com\n" +
"becukwai.com\n" +
"beefungames.com\n" +
"beisen.com\n" +
"beizi.biz\n" +
"benber-tech.com\n" +
"bendibao.com\n" +
"bensiea.com\n" +
"beschannels.com\n" +
"bestdo.com\n" +
"bestedm.net\n" +
"bestsuppliers.com\n" +
"beyondh.com\n" +
"bfvvs.com\n" +
"bhccn.com\n" +
"bhsr.com\n" +
"bi-sage.site\n" +
"bidchance.com\n" +
"bidizhaobiao.com\n" +
"bieshu.com\n" +
"bigcakegame.com\n" +
"bigda.com\n" +
"bigdatacq.com\n" +
"bigesj.com\n" +
"biggerlens.com\n" +
"bignox.com\n" +
"bigo.sg\n" +
"bigo.tv\n" +
"bigolive.tv\n" +
"biliapi.com\n" +
"biliapi.net\n" +
"bilibili.com\n" +
"bilibiligame.net\n" +
"bilibilihelper.com\n" +
"bilicdn1.com\n" +
"bilicdn2.com\n" +
"biligame.com\n" +
"biligame.net\n" +
"biliimg.com\n" +
"biliintl.com\n" +
"bilivideo.com\n" +
"bingdoc.com\n" +
"binstream.live\n" +
"bio-protocol.org\n" +
"bioon.com\n" +
"bitauto.com\n" +
"bitautoimg.com\n" +
"bitbrowser.net\n" +
"biubiu001.com\n" +
"biz-email.net\n" +
"biz72.com\n" +
"bizcn.com\n" +
"bj-sydc.com\n" +
"bj-tencentclb.cloud\n" +
"bj-tencentclb.com\n" +
"bj-tencentclb.net\n" +
"bj003.com\n" +
"bjcathay.com\n" +
"bjjubao.org\n" +
"bjmantis.net\n" +
"bjmxy.net\n" +
"bjtelecom.net\n" +
"bjyyb.net\n" +
"bjzghd.com\n" +
"blackshark.com\n" +
"bldimg.com\n" +
"bldpharm.com\n" +
"blmpb.com\n" +
"blued.com\n" +
"bluesoleil.com\n" +
"bmcx.com\n" +
"bmlink.com\n" +
"bmp.ovh\n" +
"boce.com\n" +
"bohrium.com\n" +
"bokecc.com\n" +
"bokee.net\n" +
"bonree.com\n" +
"boohee.com\n" +
"book118.com\n" +
"bootcdn.net\n" +
"bootcss.com\n" +
"boox.com\n" +
"boqii.com\n" +
"boqiicdn.com\n" +
"bossgoo.com\n" +
"bosszhipin.com\n" +
"botslab.com\n" +
"bpaykwai.com\n" +
"bpmlt.com\n" +
"bq04.com\n" +
"brg0.com\n" +
"bricksball.com\n" +
"bsccdn.com\n" +
"bscdnweb.com\n" +
"bscedge.com\n" +
"bscgslb.com\n" +
"bscstorage.net\n" +
"bsgslb.com\n" +
"bspapp.com\n" +
"bstatic.com\n" +
"bstatics.com\n" +
"btrbdf.com\n" +
"buluken.com\n" +
"bus84.com\n" +
"bvfcdn.com\n" +
"bvfcdn2.com\n" +
"bvglb.com\n" +
"bvgtm.com\n" +
"bwton.com\n" +
"bxsnews.com\n" +
"bxtag.com\n" +
"bybieyang.com\n" +
"byd.auto\n" +
"byd.com\n" +
"byte-test.com\n" +
"byte008.com\n" +
"byteacctimg.com\n" +
"byteadverts.com\n" +
"bytecdn.com\n" +
"bytecdntp.com\n" +
"byted-static.com\n" +
"byted-ug.com\n" +
"bytedance.com\n" +
"bytedance.net\n" +
"bytedanceapi.com\n" +
"bytedancevod.com\n" +
"bytedcdn.com\n" +
"bytedns.com\n" +
"bytedns.net\n" +
"bytedns1.com\n" +
"bytedns3.com\n" +
"bytednsdoc.com\n" +
"byteeffecttos.com\n" +
"bytefae.com\n" +
"bytefcdn.com\n" +
"bytefcdnrd.com\n" +
"bytegecko.com\n" +
"bytegeckoext.com\n" +
"bytegle.site\n" +
"bytegle.tech\n" +
"bytegoofy.com\n" +
"bytegslb.com\n" +
"bytehwm.com\n" +
"byteimg.com\n" +
"bytelb.net\n" +
"bytemaimg.com\n" +
"bytemastatic.com\n" +
"bytescm.com\n" +
"bytesfield.com\n" +
"bytesus.com\n" +
"bytetcc.com\n" +
"bytetos.com\n" +
"bytevdn.com\n" +
"bytexns.com\n" +
"byxx.com\n" +
"bzxz.net\n" +
"c-ctrip.com\n" +
"c360dn.com\n" +
"c3pool.org\n" +
"c7878.com\n" +
"ca800.com\n" +
"cainiao.com\n" +
"caixin.com\n" +
"caiyunai.com\n" +
"caiyunapp.com\n" +
"caiyuncdn.com\n" +
"caiyunhub.com\n" +
"calorietech.com\n" +
"camera360.com\n" +
"camoryapps.com\n" +
"camscanner.com\n" +
"can-dao.com\n" +
"cang.com\n" +
"cangshui.net\n" +
"cangxiaoer.com\n" +
"caoliao.net\n" +
"capitalonline.net\n" +
"cargosmart.com\n" +
"cartx.cloud\n" +
"casbin.org\n" +
"casdoor.com\n" +
"catl.com\n" +
"cato-chem.com\n" +
"cbi360.net\n" +
"cbxs.net\n" +
"ccb.com\n" +
"ccement.com\n" +
"ccidnet.com\n" +
"ccmdls.adobe.com\n" +
"ccnpic.com\n" +
"ccrgt.com\n" +
"cctbn.com\n" +
"cctv.com\n" +
"cctvpic.com\n" +
"ccwow.cc\n" +
"cdfsunrise.com\n" +
"cdlgp.com\n" +
"cdn-gw-dv.vip\n" +
"cdn.samsung.com\n" +
"cdn20.com\n" +
"cdn20.org\n" +
"cdn2020.com\n" +
"cdn30.com\n" +
"cdn30.org\n" +
"cdnbuild.net\n" +
"cdnbye.com\n" +
"cdnclouds.net\n" +
"cdndm5.com\n" +
"cdndm5.net\n" +
"cdndns.vip\n" +
"cdnetdns.net\n" +
"cdnetworks.net\n" +
"cdnf.cc\n" +
"cdngslb.com\n" +
"cdngtm.com\n" +
"cdnhwc1.com\n" +
"cdnhwc2.com\n" +
"cdnhwc3.com\n" +
"cdnhwc5.com\n" +
"cdnhwc6.com\n" +
"cdnhwc8.com\n" +
"cdnhwc9.com\n" +
"cdnhwcajk17.com\n" +
"cdnhwcbqs106.com\n" +
"cdnhwcbzj102.com\n" +
"cdnhwcchh18.com\n" +
"cdnhwccmz121.com\n" +
"cdnhwcedi10.com\n" +
"cdnhwcggk22.com\n" +
"cdnhwcgqa21.com\n" +
"cdnhwchcg02.com\n" +
"cdnhwcibv122.com\n" +
"cdnhwcjog12.com\n" +
"cdnhwcljk104.com\n" +
"cdnhwcllh11.com\n" +
"cdnhwclxu105.com\n" +
"cdnhwclxw05.com\n" +
"cdnhwcoem01.com\n" +
"cdnhwcohm19.com\n" +
"cdnhwcoph123.com\n" +
"cdnhwcprh113.com\n" +
"cdnhwcpsd13.com\n" +
"cdnhwcqwg14.com\n" +
"cdnhwctnm107.com\n" +
"cdnhwcuim119.com\n" +
"cdnhwcupf06.com\n" +
"cdnhwcvix16.com\n" +
"cdnhwcxcy07.com\n" +
"cdnhwczba04.com\n" +
"cdnhwcztu09.com\n" +
"cdnhwczxh101.com\n" +
"cdnjtzy.com\n" +
"cdntip.com\n" +
"cdntips.com\n" +
"cdntips.net\n" +
"cdnudns.com\n" +
"cdnwaf.net\n" +
"ceair.com\n" +
"cebbank.com\n" +
"cece.com\n" +
"cedock.com\n" +
"cellocation.com\n" +
"centanet.com\n" +
"centauriglobal.com\n" +
"ceracdn.net\n" +
"cernet.net\n" +
"cf-ns.com\n" +
"cfluid.com\n" +
"cfogc.com\n" +
"cgtn.com\n" +
"ch.com\n" +
"chagee.com\n" +
"chaincatcher.com\n" +
"chaitin.com\n" +
"changan.biz\n" +
"changba.com\n" +
"changdunovel.com\n" +
"changhong.com\n" +
"changshang.com\n" +
"changyou.com\n" +
"chanjet.com\n" +
"chaoxing.com\n" +
"chasedream.com\n" +
"chatglm.site\n" +
"chatnos.com\n" +
"chazidian.com\n" +
"chaziyu.com\n" +
"che168.com\n" +
"cheetahgo.net\n" +
"chehejia.com\n" +
"chem17.com\n" +
"chem960.com\n" +
"chembk.com\n" +
"chemicalbook.com\n" +
"chemnet.com\n" +
"chemsrc.com\n" +
"chengzijianzhan.com\n" +
"chenzhongtech.com\n" +
"cheshi.com\n" +
"chillyroom.com\n" +
"china-embassy.org\n" +
"china-pub.com\n" +
"china-vo.org\n" +
"china-ws.org\n" +
"china.com\n" +
"chinaacc.com\n" +
"chinabgao.com\n" +
"chinacoal.com\n" +
"chinadidao.com\n" +
"chinaflier.com\n" +
"chinagoods.com\n" +
"chinahiyou.com\n" +
"chinahrt.com\n" +
"chinairn.com\n" +
"chinakong.com\n" +
"chinamae.com\n" +
"chinamobile.com\n" +
"chinamobiledevice.com\n" +
"chinanetcenter.com\n" +
"chinanetsun.com\n" +
"chinanews.com\n" +
"chinaoct.com\n" +
"chinaplasonline.com\n" +
"chinapp.com\n" +
"chinaqigong.com\n" +
"chinaso.com\n" +
"chinatelecomglobal.com\n" +
"chinatikfans.com\n" +
"chinaums.com\n" +
"chinaxinge.com\n" +
"chinaxiv.org\n" +
"chinaz.com\n" +
"chinaz.net\n" +
"chiphell.com\n" +
"chizhouren.com\n" +
"chuangcdn.com\n" +
"chuangyuejoy.com\n" +
"chuansong.me\n" +
"chuanyinet.com\n" +
"chuimg.com\n" +
"chujingapp.com\n" +
"chukouplus.com\n" +
"chunyuyisheng.com\n" +
"chyxx.com\n" +
"cibfintech.com\n" +
"cibntv.net\n" +
"ciccwm.com\n" +
"cifnews.com\n" +
"cip.cc\n" +
"cippe.net\n" +
"cirs-group.com\n" +
"citicbank.com\n" +
"citics.com\n" +
"citicsf.com\n" +
"citicsinfo.com\n" +
"city8.com\n" +
"cjdropshipping.com\n" +
"cjia.com\n" +
"cjjd14.com\n" +
"cjjhb.com\n" +
"cl2009.com\n" +
"cldisk.com\n" +
"clewm.net\n" +
"cli.im\n" +
"clickwifi.net\n" +
"clngaa.com\n" +
"cloud-links.net\n" +
"cloud-rtc.com\n" +
"cloud-rtc.net\n" +
"cloud-scdn.com\n" +
"cloudcachetci.com\n" +
"cloudcsp.com\n" +
"clouddn.com\n" +
"cloudflare-cn.com\n" +
"cloudflareanycast.net\n" +
"cloudflarecn.net\n" +
"cloudflareperf.com\n" +
"cloudlvs.com\n" +
"cloudses.com\n" +
"cloudstudio.club\n" +
"cloudvdn.com\n" +
"cmbchina.com\n" +
"cmbimg.com\n" +
"cmcm.com\n" +
"cmedns.com\n" +
"cmes.org\n" +
"cmgadx.com\n" +
"cmhk.com\n" +
"cmicapm.com\n" +
"cmpassport.com\n" +
"cmpay.com\n" +
"cmread.com\n" +
"cmschina.com\n" +
"cn-msedge.net\n" +
"cn.bing.com\n" +
"cn.bing.net\n" +
"cn.mm.bing.net\n" +
"cn.net\n" +
"cn.pool.ntp.org\n" +
"cn4e.com\n" +
"cnal.com\n" +
"cname-cdn.com\n" +
"cname123.net\n" +
"cname88.com\n" +
"cnb.cool\n" +
"cnblogs.com\n" +
"cnccdn.com\n" +
"cncdn.com\n" +
"cncn.com\n" +
"cncnet.net\n" +
"cndns5.com\n" +
"cndzys.com\n" +
"cnfeol.com\n" +
"cnfol.com\n" +
"cngold.org\n" +
"cngoldres.com\n" +
"cngslb.com\n" +
"cnhis.cc\n" +
"cnhnb.com\n" +
"cninfo.net\n" +
"cniti.com\n" +
"cnjournals.com\n" +
"cnkang.com\n" +
"cnkeyboard.com\n" +
"cnki.net\n" +
"cnklog.com\n" +
"cnlaunch.com\n" +
"cnmo.com\n" +
"cnmobile.net\n" +
"cnmsn.net\n" +
"cnmstl.net\n" +
"cnolnic.com\n" +
"cnpereading.com\n" +
"cnstock.com\n" +
"cntaiping.com\n" +
"cnuninet.net\n" +
"cnzz.com\n" +
"co188.com\n" +
"cocos.com\n" +
"coding-pages.com\n" +
"codmwest.com\n" +
"cofco.com\n" +
"coffeejp.com\n" +
"cofile.net\n" +
"coinall.ltd\n" +
"colipu.com\n" +
"colorfulclouds.net\n" +
"coloros.com\n" +
"comfylink.com\n" +
"compassedu.hk\n" +
"compgoo.com\n" +
"confluxrpc.com\n" +
"contentchina.com\n" +
"coocaa.com\n" +
"coocare.com\n" +
"coocent.net\n" +
"coofandy.com\n" +
"cool-de.com\n" +
"coolbcloud.com\n" +
"coolccloud.com\n" +
"coolkit.cc\n" +
"coolpad.com\n" +
"coolzcloud.com\n" +
"cootekservice.com\n" +
"coovee.com\n" +
"coros.com\n" +
"coscoshipping.com\n" +
"coze.site\n" +
"cpatrk.net\n" +
"cpcphone.com\n" +
"cpooo.com\n" +
"cpp32.com\n" +
"cqhkcdns.com\n" +
"cqnews.net\n" +
"cqsjd.xyz\n" +
"cqttech.com\n" +
"cqvip.com\n" +
"cravatar.com\n" +
"cread.com\n" +
"creality.com\n" +
"crealitycloud.com\n" +
"crl.globalsign.net\n" +
"crl.kaspersky.com\n" +
"crntt.com\n" +
"crtrcloud.com\n" +
"crxsoso.com\n" +
"cs2-aipn.com\n" +
"csair.com\n" +
"csc108.com\n" +
"cscan.co\n" +
"cscec.com\n" +
"csdn.net\n" +
"csisolar.com\n" +
"csjdeveloper.com\n" +
"csjplatform.com\n" +
"cstimer.net\n" +
"csvw.com\n" +
"csyrtcs.com\n" +
"cszpra.com\n" +
"ctdcdn.com\n" +
"ctfile.com\n" +
"ctgcdn.com\n" +
"ctiforum.com\n" +
"ctldl.windowsupdate.com\n" +
"ctobsnssdk.com\n" +
"ctrip.com\n" +
"ctripgslb.net\n" +
"ctripins.com\n" +
"cvtapi.com\n" +
"cvte.com\n" +
"cxkfwn.com\n" +
"cy-isp.com\n" +
"cyol.com\n" +
"cz88.net\n" +
"czhaobiao.com\n" +
"d-ctrip.com\n" +
"d17.cc\n" +
"d3f.com\n" +
"d5render.com\n" +
"d5xs.net\n" +
"d777.com\n" +
"da.anythinktech.com\n" +
"dadacart.com\n" +
"dahecube.com\n" +
"dahhxxttxs.com\n" +
"dahuaddns.com\n" +
"dahuap2p.com\n" +
"dahuap2pcloud.com\n" +
"dahuatech.com\n" +
"dailygn.com\n" +
"dalyfeds.com\n" +
"damddos.com\n" +
"dancf.com\n" +
"danchuangglobal.com\n" +
"dangbei.com\n" +
"dangbei.net\n" +
"dangdang.com\n" +
"daodoc.com\n" +
"daojishiwang.com\n" +
"daraz.com\n" +
"daraz.lk\n" +
"daraz.pk\n" +
"darryring.com\n" +
"dashisx.com\n" +
"datacaciques.com\n" +
"datahubtrack.com\n" +
"dataodu.com\n" +
"datk.anythinktech.com\n" +
"dav01.com\n" +
"daxuelu.com\n" +
"dayainfo.com\n" +
"dayoo.com\n" +
"dayscamera.com\n" +
"dayu.com\n" +
"dayugslb.com\n" +
"dbank.com\n" +
"dbankcdn.com\n" +
"dbankcdn.ru\n" +
"dbankcloud.asia\n" +
"dbankcloud.com\n" +
"dbankcloud.eu\n" +
"dbankcloud.ru\n" +
"dbankedge.net\n" +
"dbscar.com\n" +
"dcarapi.com\n" +
"dcarimg.com\n" +
"dcarstatic.com\n" +
"dcg.microsoft.com\n" +
"dcloud.io\n" +
"dcloudlive.com\n" +
"dcloudstc.com\n" +
"dd373.com\n" +
"ddblquge.cc\n" +
"ddimg.mobi\n" +
"ddosjq.xyz\n" +
"ddxq.mobi\n" +
"de-tencentclb.cloud\n" +
"de-tencentclb.com\n" +
"de-tencentclb.net\n" +
"deepcool.com\n" +
"deepin.com\n" +
"deepin.org\n" +
"deepinstall.com\n" +
"deepleaper.com\n" +
"deepseek.com\n" +
"deepseeksvc.com\n" +
"delicloud.com\n" +
"denza.com\n" +
"design006.com\n" +
"detailroi.com\n" +
"dewmobile.net\n" +
"dewu.com\n" +
"dewucdn.com\n" +
"deyecloud.com\n" +
"deyi.com\n" +
"dfcfw.com\n" +
"dftzj.com\n" +
"dgsltx.com\n" +
"dhrest.com\n" +
"diandian.com\n" +
"dianping.com\n" +
"dianwanshidai.com\n" +
"dianxiaomi.com\n" +
"dianzhangzhipin.com\n" +
"dida365.com\n" +
"didi-food.com\n" +
"didialift.com\n" +
"didiapp.com\n" +
"didichuxing.com\n" +
"didifinance.com\n" +
"didiglobal.com\n" +
"didistatic.com\n" +
"didiwuxian.com\n" +
"didiyun.com\n" +
"digitimetech.com\n" +
"digiwin.com\n" +
"dimg04.tripcdn.com\n" +
"dingrtc.com\n" +
"dingtalk.com\n" +
"dingtalkapps.com\n" +
"dingxiang-inc.com\n" +
"ditu.live.com\n" +
"diyifanwen.com\n" +
"diyifanwen.net\n" +
"diymysite.com\n" +
"dizgslb.com\n" +
"dji.com\n" +
"dji.net\n" +
"djicdn.com\n" +
"djigate.com\n" +
"djiits.com\n" +
"djiops.com\n" +
"djiservice.org\n" +
"dl.delivery.mp.microsoft.com\n" +
"dlszywz.com\n" +
"dm5.com\n" +
"dmall.com\n" +
"dmgytb.com\n" +
"dmrtb.com\n" +
"dmzj.com\n" +
"dns.com\n" +
"dns.pub\n" +
"dnsapi12.com\n" +
"dnse0.com\n" +
"dnse1.com\n" +
"dnse2.com\n" +
"dnse3.com\n" +
"dnse4.com\n" +
"dnse5.com\n" +
"dnsmeasurement.com\n" +
"dnsoe4.com\n" +
"dnsoe5.com\n" +
"dnsoe6.com\n" +
"dnspod.com\n" +
"dnspod.net\n" +
"dnsv1.com\n" +
"dnsv2.com\n" +
"dnsv3.com\n" +
"dnsv4.com\n" +
"dnsv5.com\n" +
"dnsvcache.com\n" +
"dnsvhost.com\n" +
"dobunkan.com\n" +
"doc88.com\n" +
"docer.com\n" +
"docin.com\n" +
"doglobal.net\n" +
"doh.pub\n" +
"dolfincdnx.com\n" +
"dollphoin.site\n" +
"dolphin-browser.com\n" +
"dongao.com\n" +
"dongchedi.com\n" +
"dongdianqiu.com\n" +
"dongfangfuli.com\n" +
"dongfou.com\n" +
"dongqiudi.com\n" +
"dooland.com\n" +
"dot.pub\n" +
"douban.com\n" +
"doubanio.com\n" +
"doubao-dev.com\n" +
"doubao.com\n" +
"doubaocdn.com\n" +
"doudou520.online\n" +
"douguo.com\n" +
"doupay.com\n" +
"douyin.com\n" +
"douyincdn.com\n" +
"douyinec.com\n" +
"douyinliving.com\n" +
"douyinmusicpromotion.com\n" +
"douyinpic.com\n" +
"douyinstatic.com\n" +
"douyinvod.com\n" +
"douyu.com\n" +
"dowater.com\n" +
"download.microsoft.com\n" +
"download.visualstudio.microsoft.com\n" +
"download.windowsupdate.com\n" +
"downxia.com\n" +
"dpfile.com\n" +
"draftstatic.com\n" +
"dreambig.work\n" +
"dreame.tech\n" +
"drivergenius.com\n" +
"drivers.amd.com\n" +
"drivethelife.com\n" +
"droiapps.com\n" +
"droiseewd.com\n" +
"droiyou.com\n" +
"drugfuture.com\n" +
"dsers.com\n" +
"dtstatic.com\n" +
"dualaid.com\n" +
"duapp.com\n" +
"duapps.com\n" +
"duba.com\n" +
"duba.net\n" +
"duitang.com\n" +
"dun222.com\n" +
"dun555.com\n" +
"duoduocdn.com\n" +
"duokan.com\n" +
"duokanbox.com\n" +
"duole.com\n" +
"duomai.com\n" +
"duowan.com\n" +
"duoyi.com\n" +
"dushu.com\n" +
"dushu365.com\n" +
"dustess.com\n" +
"dutils.com\n" +
"duxiaoman.com\n" +
"duxiaomanfintech.com\n" +
"duxiu.com\n" +
"dvr163.com\n" +
"dvrdydns.com\n" +
"dxm-yibai.com\n" +
"dxmpay.com\n" +
"dxycdn.com\n" +
"dywzx.com\n" +
"dzdu.com\n" +
"dzgxq.com\n" +
"dzsc.com\n" +
"dzw3.com\n" +
"dzwww.com\n" +
"dzxwnews.com\n" +
"e-chinalife.com\n" +
"e-seenet.com\n" +
"e-sscard.com\n" +
"e2esoft.com\n" +
"eagllwin.com\n" +
"easemob.com\n" +
"easeslb.com\n" +
"easeus.com\n" +
"easipass.com\n" +
"easiu.com\n" +
"eastday.com\n" +
"eastmoney.com\n" +
"eastmoneysec.com\n" +
"easyar.com\n" +
"easyeda.com\n" +
"easygame2021.com\n" +
"easyliao.com\n" +
"easyscholar.cc\n" +
"easytomessage.com\n" +
"ebaixing.com\n" +
"ebdoor.com\n" +
"ebscn.com\n" +
"ebuckler.com\n" +
"eccang.com\n" +
"eccdnx.com\n" +
"ecdnx.com\n" +
"ecer.com\n" +
"ecerdns.com\n" +
"ecerimg.com\n" +
"echatsoft.com\n" +
"echinagov.com\n" +
"ecitic.com\n" +
"eckwai.com\n" +
"ecombdapi.com\n" +
"ecombdimg.com\n" +
"ecombdpage.com\n" +
"ecombdstatic.com\n" +
"ecombdvod.com\n" +
"ecouser.net\n" +
"ecovacs.com\n" +
"ecukwai.com\n" +
"edge-byted.com\n" +
"edge-cluster-hk-pre.com\n" +
"edgekey88.net\n" +
"edgeone.app\n" +
"edgeonedy1.com\n" +
"edifier.com\n" +
"edimob.com\n" +
"edrawsoft.com\n" +
"edu24ol.com\n" +
"eduease.com\n" +
"ee1234.com\n" +
"eebbk.net\n" +
"eeff.net\n" +
"eefocus.com\n" +
"eenzo.com\n" +
"effirst.com\n" +
"eicp.net\n" +
"ejia7.net\n" +
"ejoy.com\n" +
"ele.me\n" +
"elecfans.com\n" +
"elemecdn.com\n" +
"elex-tech.net\n" +
"elimautism.org\n" +
"elong.com\n" +
"elongstatic.com\n" +
"emqx.cloud\n" +
"emqx.com\n" +
"emtana.com\n" +
"enacdn.net\n" +
"ename.com\n" +
"ename.net\n" +
"eo-edgefunctions7.com\n" +
"eoffcn.com\n" +
"epday.com\n" +
"eqxiu.com\n" +
"erji.net\n" +
"eshimin.com\n" +
"eshow365.com\n" +
"eshukan.com\n" +
"estrongs.com\n" +
"etoote.com\n" +
"etrack05.com\n" +
"ettdnsv.com\n" +
"eudic.net\n" +
"ev123.com\n" +
"everychina.com\n" +
"evtrust.com\n" +
"evyy.net\n" +
"excelhome.net\n" +
"exezhanqun.com\n" +
"externalcoop.com\n" +
"eybond.com\n" +
"eyou.com\n" +
"eyugame.com\n" +
"ezcname.com\n" +
"ezviz.com\n" +
"f.c2r.ts.cdn.office.net\n" +
"f.cx\n" +
"f3322.net\n" +
"f3322.org\n" +
"fabao365.com\n" +
"faceu.com\n" +
"faceu.mobi\n" +
"faceunity.com\n" +
"faidns.com\n" +
"faipod.com\n" +
"faisys.com\n" +
"faiusr.com\n" +
"falconnet.app\n" +
"faloo.com\n" +
"famens.com\n" +
"fancyapi.com\n" +
"fancydsp.com\n" +
"fang.com\n" +
"fangxiaoer.com\n" +
"fanli.com\n" +
"fanqienovel.com\n" +
"fanqiesdk.com\n" +
"fanqiesdkpic.com\n" +
"fanruan.com\n" +
"fantanggame.com\n" +
"fante.com\n" +
"fas-bee.com\n" +
"fastapi.net\n" +
"fastliii.com\n" +
"fastsdwan.com\n" +
"faststatics.com\n" +
"faw-vw.com\n" +
"fblife.com\n" +
"fcapp.run\n" +
"fcbox.com\n" +
"fccs.com\n" +
"fckpw.com\n" +
"fclouddns.net\n" +
"feedcoopapi.com\n" +
"feidee.com\n" +
"feidee.net\n" +
"feikua.net\n" +
"feimogames.com\n" +
"feipinzhan.com\n" +
"feishu-3rd-party-services.com\n" +
"feishu.net\n" +
"feishucdn.com\n" +
"feishupkg.com\n" +
"feizhu.com\n" +
"felicitysolar.com\n" +
"fenbi.com\n" +
"fengjinketang.com\n" +
"fengkongcloud.com\n" +
"fengniao.com\n" +
"fenxi.com\n" +
"fenzijr.com\n" +
"ffzww.com\n" +
"fh21.com\n" +
"file.tripcdn.com\n" +
"filfox.info\n" +
"fintopia.tech\n" +
"finzfin.com\n" +
"firwinds.site\n" +
"fkw.com\n" +
"fleetlogd.com\n" +
"fliggy.com\n" +
"flmgr.net\n" +
"floatcamellia.com\n" +
"floatingislandapps.com\n" +
"flowerknows.co\n" +
"flydigi.com\n" +
"flyme.com\n" +
"fnnas.com\n" +
"fnos.net\n" +
"fobshanghai.com\n" +
"fofa.info\n" +
"fogcloud.io\n" +
"foisonad.com\n" +
"font.im\n" +
"fontke.com\n" +
"foodjx.com\n" +
"foodmate.net\n" +
"forcloudcdn.com\n" +
"ford.com\n" +
"forevernine.com\n" +
"fotomore.com\n" +
"foundersc.com\n" +
"four-faith.com\n" +
"foxconn.com\n" +
"foxmail.com\n" +
"fqnovel.com\n" +
"fqnovelpic.com\n" +
"fqnovelstatic.com\n" +
"fqnovelvod.com\n" +
"fr-trading.com\n" +
"frdic.com\n" +
"freshippo.com\n" +
"frigidpine.com\n" +
"fsou.com\n" +
"fspage.com\n" +
"fuioupay.com\n" +
"fun.tv\n" +
"funcrea.com\n" +
"funnysphere.com\n" +
"funshion.com\n" +
"funshion.net\n" +
"fupanwang.com\n" +
"futuau.com\n" +
"futufin.com\n" +
"futuhn.com\n" +
"futunn.com\n" +
"futustatic.com\n" +
"fxbaogao.com\n" +
"fxiaoke.com\n" +
"fxltsbl.com\n" +
"fyun.cc\n" +
"gaapqcloud.com\n" +
"gaetausohyei.com\n" +
"gafei.com\n" +
"gaiaworkforce.com\n" +
"galaxy-immi.com\n" +
"galaxyappstore.com\n" +
"gamecat.fun\n" +
"gamekee.com\n" +
"gamekuaishou.com\n" +
"gamelet.games\n" +
"gameley.com\n" +
"gameloop.com\n" +
"gamepp.com\n" +
"gamersky.com\n" +
"ganji.com\n" +
"gankao.com\n" +
"gaode.com\n" +
"gaoding.com\n" +
"gaodun.com\n" +
"gaofangm.com\n" +
"gaofangz.com\n" +
"gaokao.com\n" +
"gaomon.net\n" +
"gaopaiwood.com\n" +
"gaoxiaojob.com\n" +
"gasgoo.com\n" +
"gaxify.com\n" +
"gccdn.net\n" +
"gcdcrs.com\n" +
"gcloudcache.com\n" +
"gcloudcs.com\n" +
"gcloudgbs.com\n" +
"gcloudsdk.com\n" +
"gcloudsvcs.com\n" +
"gdmm.com\n" +
"gdrc.com\n" +
"gdtimg.com\n" +
"gdyhsp.com\n" +
"geeetech.com\n" +
"geely.com\n" +
"geetest.com\n" +
"geevisit.com\n" +
"geilicdn.com\n" +
"gelonghui.com\n" +
"genscript.com\n" +
"geo.kaspersky.com\n" +
"geovisearth.com\n" +
"gepush.com\n" +
"gerenjianli.com\n" +
"get.vip\n" +
"getui.com\n" +
"getui.net\n" +
"gezila.com\n" +
"gg.com\n" +
"ghxi.com\n" +
"gicp.net\n" +
"gifshow.com\n" +
"giikin.com\n" +
"giocdn.com\n" +
"giordano.com\n" +
"gitcode.com\n" +
"gitee.com\n" +
"giteeusercontent.com\n" +
"gitv.tv\n" +
"gizwits.com\n" +
"gkong.com\n" +
"gkzhan.com\n" +
"glb4.com\n" +
"global-download.acer.com\n" +
"globalsign.com\n" +
"globalsigncdn.com\n" +
"globalslb.net\n" +
"globalso.com\n" +
"globalso.site\n" +
"globalsources.com\n" +
"glodon.com\n" +
"glowapp.vip\n" +
"gmdt9b.com\n" +
"gmertc.com\n" +
"gnway.cc\n" +
"gnway.org\n" +
"go2yd.com\n" +
"goepe.com\n" +
"goforandroid.com\n" +
"goho.co\n" +
"goldhoe.com\n" +
"goldsupplier.com\n" +
"gomo.com\n" +
"gomocdn.com\n" +
"gongboshi.com\n" +
"gongkaoleida.com\n" +
"gongkong.com\n" +
"gongyelian.com\n" +
"gonxt.com\n" +
"goodao.net\n" +
"goodcloud.xyz\n" +
"goodwe.com\n" +
"goofish.com\n" +
"goolink.org\n" +
"gotocdn.com\n" +
"gotohui.com\n" +
"gotoip1.com\n" +
"gotoip11.com\n" +
"gotoip2.com\n" +
"gotoip3.com\n" +
"gotoip4.com\n" +
"gotoip55.com\n" +
"gotokeep.com\n" +
"gotvg.com\n" +
"goufang.com\n" +
"gougoujp.com\n" +
"gov-static.tech\n" +
"goweb2.net\n" +
"gpsonextra.net\n" +
"gpubgm.com\n" +
"gravity-engine.com\n" +
"gree.com\n" +
"gridsumdissector.com\n" +
"growatt.com\n" +
"growingio.com\n" +
"gryphline.com\n" +
"gs2.ww.prod.dl.playstation.net\n" +
"gsensebot.com\n" +
"gshdw.cyou\n" +
"gskwai.com\n" +
"gspaceteam.com\n" +
"gst.prod.dl.playstation.net\n" +
"gstarcad.com\n" +
"gtarcade.com\n" +
"gter.net\n" +
"gtht.com\n" +
"gtimg.com\n" +
"gtja.com\n" +
"gtjadev.com\n" +
"gtm-a2b2.com\n" +
"gtm-a2b4.com\n" +
"gtm-a4b8.com\n" +
"gtm-i1d9.com\n" +
"guahao.com\n" +
"guahaoe.com\n" +
"guaili.org\n" +
"guance.com\n" +
"guangdongyunchen.com\n" +
"guangka.com\n" +
"guangqiapp.com\n" +
"guangtuikeji.com\n" +
"guangxunsd.com\n" +
"guangyacdn.com\n" +
"guangyv.com\n" +
"guangzhuiyuan.com\n" +
"guanwang.cc\n" +
"guardease.com\n" +
"guazi.com\n" +
"guazistatic.com\n" +
"guidechem.com\n" +
"gushiju.net\n" +
"gusspro.com\n" +
"guzwiayz.com\n" +
"gvoiceplat.com\n" +
"gvt1-cn.com\n" +
"gw-dv.vip\n" +
"gwdang.com\n" +
"gwmapp-h.com\n" +
"gxfinfr.com\n" +
"gxhouse.com\n" +
"gxjcxy.com\n" +
"gz-tencentclb.com\n" +
"gz-tencentclb.net\n" +
"gzhfschool.com\n" +
"gzkuaiyingyong.com\n" +
"gzmama.com\n" +
"gzxianc.com\n" +
"h2os.com\n" +
"h3c.com\n" +
"haidii.com\n" +
"haier.com\n" +
"haier.net\n" +
"hailuoai.com\n" +
"haimacloud.com\n" +
"haimawan.com\n" +
"halomobi.com\n" +
"hangzhoumengfa.com\n" +
"hansong-china.com\n" +
"hanspub.org\n" +
"hao123.com\n" +
"hao184.com\n" +
"hao86.com\n" +
"haodf.com\n" +
"haodns999.cc\n" +
"haohanpower.tech\n" +
"haoranbio.com\n" +
"haosou.com\n" +
"haplat.net\n" +
"happyelements.com\n" +
"hardcoresir.net\n" +
"hasea.com\n" +
"hawjob.com\n" +
"hbidc.net\n" +
"hbrsks.net\n" +
"hbzhan.com\n" +
"hc-cdn.com\n" +
"hcicloud.com\n" +
"hcwebsite.com\n" +
"hdslb.com\n" +
"hdtgtm.com\n" +
"healthjd.com\n" +
"hehagame.com\n" +
"heishenhua.com\n" +
"hellobike.com\n" +
"hellogroup.vip\n" +
"hellogslb.com\n" +
"hellotalk8.com\n" +
"helps.live\n" +
"hengrui.com\n" +
"herocoming.com\n" +
"herogame.com\n" +
"hexun.com\n" +
"heygears.com\n" +
"heytap.com\n" +
"heytapcs.com\n" +
"heytapdownload.com\n" +
"heytapimage.com\n" +
"heytapmobi.com\n" +
"hezegd.com\n" +
"hh010.com\n" +
"hhjd.mobi\n" +
"hi-spider.com\n" +
"hi1718.com\n" +
"hiaiabc.com\n" +
"hiapk.com\n" +
"hiby.com\n" +
"hichina.com\n" +
"hicloud.com\n" +
"hifi168.com\n" +
"higgsweb.com\n" +
"hihonor.com\n" +
"hihonorcdn.com\n" +
"hihonorcloud.com\n" +
"hii-go.com\n" +
"hiido.com\n" +
"hikops.com\n" +
"hikvision.com\n" +
"hisavana.com\n" +
"hisdnoc.com\n" +
"hisense.com\n" +
"hismarttv.com\n" +
"hisupplier.com\n" +
"hitv.com\n" +
"hjren.com\n" +
"hjygame.com\n" +
"hk-tencentclb.com\n" +
"hk-tencentclb.net\n" +
"hlgdata.com\n" +
"hlgnet.com\n" +
"hmlan.com\n" +
"hn165.com\n" +
"hnair.com\n" +
"hnrrco.com\n" +
"hnsoftedu.com\n" +
"hok5v5.com\n" +
"holyxiongan.com\n" +
"homestyler.com\n" +
"hongboluo.com\n" +
"hongkongairlines.com\n" +
"hongxiu.com\n" +
"hongze365.com\n" +
"honkaiimpact3.com\n" +
"honor.com\n" +
"honorfile.com\n" +
"honorofkings.com\n" +
"hoolai.com\n" +
"hoopchina.com\n" +
"horionsw.com\n" +
"hortorgames.com\n" +
"hostbbs.net\n" +
"houdao.com\n" +
"house510.com\n" +
"howlapm.com\n" +
"howxm.com\n" +
"hoyo.link\n" +
"hoyoverse.com\n" +
"hp-ww.com\n" +
"hp.com\n" +
"hpconnected.com\n" +
"hpgamestream.com\n" +
"hprt.com\n" +
"hqdoor.com\n" +
"hqew.com\n" +
"hqsmartcloud.com\n" +
"hqwx.com\n" +
"hstong.com\n" +
"ht88.com\n" +
"htsc.com\n" +
"htsec.com\n" +
"htsham.com\n" +
"httdsj.com\n" +
"httpdns.pro\n" +
"huaban.com\n" +
"huabanimg.com\n" +
"huaer.cc\n" +
"huahao.com\n" +
"huaijiufu.com\n" +
"huami.com\n" +
"huan.tv\n" +
"huangye88.com\n" +
"huanqiu.com\n" +
"huaon.com\n" +
"huaqin.com\n" +
"huatongcloud.com\n" +
"huatu.com\n" +
"huawei.asia\n" +
"huawei.com\n" +
"huawei.ru\n" +
"huaweicloud-dns.com\n" +
"huaweicloud-dns.net\n" +
"huaweicloud-dns.org\n" +
"huaweicloud.com\n" +
"huaweicloudapis.com\n" +
"huaweicloudwaf.com\n" +
"huaweidevice.com\n" +
"huaweifile.com\n" +
"huaweisafedns.com\n" +
"huaweistatic.com\n" +
"huazhu.com\n" +
"hubstudio.vip\n" +
"hugecdn168.com\n" +
"huians.com\n" +
"huijistatic.com\n" +
"huijiwiki.com\n" +
"huiju.cool\n" +
"huilianyi.com\n" +
"huion.com\n" +
"huishoushang.com\n" +
"huitu.com\n" +
"huiyiai.net\n" +
"hujiang.com\n" +
"hunan.tv\n" +
"hunantv.com\n" +
"hunbei.com\n" +
"hunliji.com\n" +
"hunlimao.com\n" +
"huocheso.com\n" +
"huodongxing.com\n" +
"huolinhe.com\n" +
"huoshanimg.com\n" +
"huoshanlive.com\n" +
"huoshanstatic.com\n" +
"hupu.com\n" +
"huxiu.com\n" +
"huxiucdn.com\n" +
"huya.com\n" +
"hwccpc.com\n" +
"hwclouds-dns.com\n" +
"hwwt8.com\n" +
"hwxc.com\n" +
"hx2car.com\n" +
"hxjxsw.com\n" +
"hxkba.com\n" +
"hyhcdn.com\n" +
"hyper3d.ai\n" +
"hypercachenode.com\n" +
"hypergryph.com\n" +
"hytera.com\n" +
"hyzhihe.com\n" +
"hzchengdun.com\n" +
"hznet.tv\n" +
"hznzcn.com\n" +
"hzshudian.com\n" +
"hzyidc.com\n" +
"hzyoka.com\n" +
"hzzfcm.com\n" +
"i4px.com\n" +
"i8tq.com\n" +
"ialicdn.com\n" +
"iask.in\n" +
"ibaotu.com\n" +
"ibicn.com\n" +
"ibidian.com\n" +
"ibroadlink.com\n" +
"ibytedapm.com\n" +
"ic37.com\n" +
"icaidao.com\n" +
"icbc-ltd.com\n" +
"icbcstandard.com\n" +
"iciba.com\n" +
"icirculation.com\n" +
"icloudv6.com\n" +
"icloudwaf.com\n" +
"icoremail.net\n" +
"icostapp.com\n" +
"icpdf.com\n" +
"ictun.com\n" +
"id6.me\n" +
"ida-a.org\n" +
"idcay.com\n" +
"idchz.com\n" +
"ideation.love\n" +
"idouqu.com\n" +
"idouyinvod.com\n" +
"idqqimg.com\n" +
"ieasyclick.net\n" +
"ieasytech.com\n" +
"iegcom.com\n" +
"ieltsonlinetests.com\n" +
"iemiq.com\n" +
"iesdouyin.com\n" +
"ietheivaicai.com\n" +
"ifedge.com\n" +
"ifeng.com\n" +
"ifengimg.com\n" +
"iflix.com\n" +
"iflyrec.com\n" +
"iflysec.com\n" +
"iflytek.com\n" +
"ifzzw.com\n" +
"igame58.com\n" +
"igamecj.com\n" +
"igetget.com\n" +
"igexin.com\n" +
"igpsport.com\n" +
"igtm-b101.com\n" +
"igtm-meeting-tencent.com\n" +
"igtm-yuanbao.com\n" +
"ihappystudio.com\n" +
"ihuaben.com\n" +
"ihuman.com\n" +
"ihuoshanlive.com\n" +
"ihwrm.com\n" +
"iiauuw.com\n" +
"iicha.com\n" +
"iikx.com\n" +
"ijinshan.com\n" +
"ik3cloud.com\n" +
"ikang.com\n" +
"ikuaimi.com\n" +
"ikutu.com\n" +
"ilifesmart.com\n" +
"imagehub.cc\n" +
"images3.tripcdn.com\n" +
"imdo.co\n" +
"imedao.com\n" +
"imeitools.com\n" +
"img-space.com\n" +
"img-static.tech\n" +
"img.samsungapps.com\n" +
"img4399.com\n" +
"imgcdc.com\n" +
"imile.com\n" +
"imkevinyang.com\n" +
"immomo.com\n" +
"imnks.com\n" +
"imolive.tv\n" +
"imoo.com\n" +
"imou.com\n" +
"imtedge.com\n" +
"imtmp.net\n" +
"imwork.net\n" +
"imycdn.com\n" +
"imyfone.club\n" +
"in.th\n" +
"infinitynewtab.com\n" +
"infoldgames.com\n" +
"inftab.com\n" +
"initaa.com\n" +
"initac.com\n" +
"initaf.com\n" +
"initah.com\n" +
"initaj.com\n" +
"initak.com\n" +
"initba.com\n" +
"initbb.com\n" +
"initcc.com\n" +
"initdd.com\n" +
"initff.com\n" +
"initgg.com\n" +
"initjj.com\n" +
"initkk.com\n" +
"initll.com\n" +
"initmm.com\n" +
"initnn.com\n" +
"initpp.com\n" +
"initqq.com\n" +
"initrr.com\n" +
"inittt.com\n" +
"inituu.com\n" +
"initvv.com\n" +
"initww.com\n" +
"initxa.com\n" +
"initxb.com\n" +
"initxx.com\n" +
"initzz.com\n" +
"inkuai.com\n" +
"inkwai.com\n" +
"inmense.site\n" +
"inping.com\n" +
"inshotapp.com\n" +
"insta360.com\n" +
"intelcupid.com\n" +
"interface003.com\n" +
"intlgame.com\n" +
"intlscdn.com\n" +
"intmedic.com\n" +
"intsig.net\n" +
"iok.la\n" +
"ip138.com\n" +
"ipadump.com\n" +
"ipdatacloud.com\n" +
"iper2.com\n" +
"ipinyou.com\n" +
"ipip.net\n" +
"iposeidonbussiness.com\n" +
"iposeidoncdn.com\n" +
"ipshu.com\n" +
"iqilu.com\n" +
"iqiyi.com\n" +
"iqiyipic.com\n" +
"iqoo.com\n" +
"ireader.com\n" +
"irisdt.com\n" +
"irisgw.com\n" +
"irlianmeng.com\n" +
"irs03.com\n" +
"isealsuite.com\n" +
"ish168.com\n" +
"ishangtong.com\n" +
"ishijing.com\n" +
"isjike.com\n" +
"iskysoft.com\n" +
"islide.cc\n" +
"isvjcloud.com\n" +
"it168.com\n" +
"itab.link\n" +
"iteye.com\n" +
"itheima.com\n" +
"ithome.com\n" +
"itigergrowtha.com\n" +
"itongcheng.cc\n" +
"itopsdk.com\n" +
"itoutiaostatic.com\n" +
"itravelsaas.com\n" +
"itzmx.com\n" +
"iwencai.com\n" +
"ixigua.com\n" +
"iyong.com\n" +
"iytcdn.com\n" +
"izatcloud.net\n" +
"izuiyou.com\n" +
"jb1000.com\n" +
"jb51.net\n" +
"jbzyw.com\n" +
"jc-saas.com\n" +
"jc35.com\n" +
"jcloud-cdn.com\n" +
"jcloudedge.com\n" +
"jcloudgslb.com\n" +
"jcloudimg.com\n" +
"jcloudlb.com\n" +
"jcloudstatic.com\n" +
"jctrans.com\n" +
"jd.com\n" +
"jd.hk\n" +
"jdapi.com\n" +
"jdbbs.com\n" +
"jdcache.com\n" +
"jdcdn.com\n" +
"jdcloud-oss.com\n" +
"jdcloud.com\n" +
"jdcloudedge.com\n" +
"jdcloudwaf.com\n" +
"jddj.com\n" +
"jdgslb.com\n" +
"jdh.com\n" +
"jdjygold.com\n" +
"jdl.com\n" +
"jdpay.com\n" +
"jdwl.com\n" +
"jdzj.com\n" +
"jellow.site\n" +
"jfdaily.com\n" +
"jfgou.com\n" +
"jftech.com\n" +
"jhscm.com\n" +
"jia.com\n" +
"jiagle.com\n" +
"jiakaobaodian.com\n" +
"jiandaoyun.com\n" +
"jianguoyun.com\n" +
"jianke.com\n" +
"jianshu.com\n" +
"jianshu.io\n" +
"jianying.com\n" +
"jianzhi8.com\n" +
"jiaoliuqu.com\n" +
"jiashule.com\n" +
"jiasule.org\n" +
"jiaxiangxm.com\n" +
"jiayuan.com\n" +
"jideos.com\n" +
"jidujiasu.com\n" +
"jiediankeji.com\n" +
"jiemian.com\n" +
"jiepei.com\n" +
"jigao616.com\n" +
"jihaoba.com\n" +
"jihuoniao.com\n" +
"jijiagames.com\n" +
"jikeiot.cloud\n" +
"jin10.com\n" +
"jingdong.com\n" +
"jingsocial.com\n" +
"jingxi.com\n" +
"jingyunyilian.com\n" +
"jinlaijinwang.com\n" +
"jinritemai.com\n" +
"jintiankansha.me\n" +
"jiuse3.cloud\n" +
"jiuweige.com\n" +
"jiuyangongshe.com\n" +
"jiwu.com\n" +
"jiyunhudong.com\n" +
"jizhimobi.com\n" +
"jjwxc.com\n" +
"jjwxc.net\n" +
"jjwxc.org\n" +
"jkcsjd.com\n" +
"jkt-tencentclb.cloud\n" +
"jkt-tencentclb.net\n" +
"jlc.com\n" +
"jlccnc.com\n" +
"jlcpcb.com\n" +
"jnesc.com\n" +
"job-sky.com\n" +
"job1001.com\n" +
"job510.com\n" +
"job5156.com\n" +
"jobui.com\n" +
"joinf.com\n" +
"jomodns.com\n" +
"jomoxc.com\n" +
"jooancloud.com\n" +
"joox.com\n" +
"jooyoo.net\n" +
"jovetech.com\n" +
"joying.com\n" +
"jp-tencentclb.com\n" +
"jpbeta.net\n" +
"jpush.io\n" +
"jrzp.com\n" +
"jscj.com\n" +
"jscnc.net\n" +
"jsd.cc\n" +
"jsdmirror.com\n" +
"jstv.com\n" +
"jsydns15.com\n" +
"jszhaobiao.com\n" +
"jtexpress.com\n" +
"jtjms-br.com\n" +
"jucdn.net\n" +
"juequling.com\n" +
"jufair.com\n" +
"juliangyinqing.com\n" +
"juming.com\n" +
"juneyaoair.com\n" +
"jupiterlauncher.com\n" +
"justalkcloud.com\n" +
"jutone.com\n" +
"juxia.com\n" +
"jxlsxy.com\n" +
"jyeoo.com\n" +
"jyip.net\n" +
"jylw.com\n" +
"jysq.net\n" +
"jz177.com\n" +
"jzcmfw.com\n" +
"k-dyn.com\n" +
"k780.com\n" +
"kajicam.com\n" +
"kantsuu.com\n" +
"kaowx.com\n" +
"kchuhai.com\n" +
"ke.com\n" +
"kechuangai.com\n" +
"keep999.com\n" +
"keepcdn.com\n" +
"kejet.net\n" +
"kekenet.com\n" +
"kenaqz.com\n" +
"keniu.com\n" +
"keyfc.net\n" +
"kfzimg.com\n" +
"kgimg.com\n" +
"kgogame.com\n" +
"khlgamen.com\n" +
"kickoffo.site\n" +
"kikuu.com\n" +
"kimi.ai\n" +
"kimi.com\n" +
"kingdee.com\n" +
"kingsoft-office-service.com\n" +
"kingsoft.com\n" +
"kingsoftstore.com\n" +
"kiphub.com\n" +
"kiwifarms.st\n" +
"kjcdn.com\n" +
"kkddosdns.com\n" +
"kkdnsv1.com\n" +
"kkmh.com\n" +
"klingai.com\n" +
"klpbbs.com\n" +
"kmail.com\n" +
"kmcha.com\n" +
"kmdns.net\n" +
"kms.pub\n" +
"knfastpic.com\n" +
"komect.com\n" +
"kongfz.com\n" +
"kookong.com\n" +
"koolearn.com\n" +
"koubei.com\n" +
"kouclo.com\n" +
"krones.com\n" +
"ks-cdn.com\n" +
"ks-live.com\n" +
"ksapisrv.com\n" +
"ksbbs.com\n" +
"ksc-test.com\n" +
"kshot.com\n" +
"kskwai.com\n" +
"ksmobile.com\n" +
"ksord.com\n" +
"ksosoft.com\n" +
"kspays.com\n" +
"kspkg.com\n" +
"ksupdate.com\n" +
"ksydns.com\n" +
"ksyun.com\n" +
"ksyuncdn.com\n" +
"ksyuncs.com\n" +
"ksyungslb.com\n" +
"ksyunv5.com\n" +
"ktcupdate.com\n" +
"kuai-ying.com\n" +
"kuaidi100.com\n" +
"kuaigames.com\n" +
"kuaikanmanhua.com\n" +
"kuaishangkf.com\n" +
"kuaishou.com\n" +
"kuaishoupay.com\n" +
"kuaishouzt.com\n" +
"kuaizhan.com\n" +
"kuajingmaihuo.com\n" +
"kugou.com\n" +
"kuiniuca.com\n" +
"kujiale.com\n" +
"kukuw.com\n" +
"kunlunaq.com\n" +
"kunlunar.com\n" +
"kunlunca.com\n" +
"kunluncan.com\n" +
"kunlunea.com\n" +
"kunlungem.com\n" +
"kunlungr.com\n" +
"kunlunhuf.com\n" +
"kunlunle.com\n" +
"kunlunno.com\n" +
"kunlunpi.com\n" +
"kunlunsl.com\n" +
"kunlunso.com\n" +
"kurobbs.com\n" +
"kurogame-service.com\n" +
"kurogame.com\n" +
"kurogame.net\n" +
"kurogame.xyz\n" +
"kurogames.com\n" +
"kuso.xyz\n" +
"kwaicdn.com\n" +
"kwaigobuy.com\n" +
"kwaiselfcdn.com\n" +
"kwaishop.com\n" +
"kwaixiaodian.com\n" +
"kwaiying.com\n" +
"kwaizt.com\n" +
"kwimgs.com\n" +
"kylinlot.com\n" +
"lagou.com\n" +
"lahuashanbx.com\n" +
"laiqukankan.com\n" +
"laiyagushi.com\n" +
"landintheair.com\n" +
"lanfeitech.com\n" +
"lanmaos.com\n" +
"lanshou.net\n" +
"lansors.com\n" +
"laohu.com\n" +
"laohu8.com\n" +
"laoyouzhibo.com\n" +
"larkoffice.com\n" +
"larksuite.com\n" +
"lazada.co.id\n" +
"lazada.co.th\n" +
"lazada.com\n" +
"lazada.com.my\n" +
"lazada.com.ph\n" +
"lazada.sg\n" +
"lazada.vn\n" +
"lazcdn.com\n" +
"lazystones.com\n" +
"lbctrl.com\n" +
"lbesec.com\n" +
"lbkrs.com\n" +
"lcftech.com\n" +
"ldgslb.com\n" +
"ldhy.click\n" +
"ldmnq.com\n" +
"ldplayer.net\n" +
"ldqxn.com\n" +
"ldycdn.com\n" +
"le.com\n" +
"leadmoad.com\n" +
"leapmotor.com\n" +
"ledu.com\n" +
"lei001.com\n" +
"leigod.com\n" +
"leiniao.com\n" +
"leiphone.com\n" +
"leisu.com\n" +
"leiting.com\n" +
"lejiashu.com\n" +
"leju.com\n" +
"lemon4.club\n" +
"leniugame.com\n" +
"lenovo.com\n" +
"lenovo.com.cdn.cloudflare.net\n" +
"lenovomm.com\n" +
"leoao-inc.com\n" +
"leoao.com\n" +
"lepudding.com\n" +
"lequ.com\n" +
"lers168.com\n" +
"letv.com\n" +
"letvlb.com\n" +
"levect.com\n" +
"levelinfinite.com\n" +
"leyoujia.com\n" +
"lf127.net\n" +
"liangle.com\n" +
"lianjia.com\n" +
"liankenet.com\n" +
"lianlianpay.com\n" +
"lianwifi.com\n" +
"liblib.art\n" +
"libsou.com\n" +
"liebiao.com\n" +
"lieju.com\n" +
"liepin.com\n" +
"lietou-static.com\n" +
"lightstrade.com\n" +
"lightyy.com\n" +
"like.video\n" +
"likecs.com\n" +
"likee.video\n" +
"likuso.com\n" +
"lilacbbs.com\n" +
"lilisi.com\n" +
"lilith.com\n" +
"lilithgame.com\n" +
"lilithgames.com\n" +
"lingjuad.com\n" +
"lingnanpass.com\n" +
"lingxigames.com\n" +
"linkbroad.com\n" +
"linkbux.com\n" +
"linkedme.cc\n" +
"linkhaitao.com\n" +
"linkrall-trk.com\n" +
"linovelib.com\n" +
"litecdncname.com\n" +
"litemob.net\n" +
"litessl.com\n" +
"livehwc4.com\n" +
"liveme.com\n" +
"lixiang.com\n" +
"lizhi.fm\n" +
"lizhifm.com\n" +
"lizihang.com\n" +
"ljcdn.com\n" +
"lkcoffee.com\n" +
"lkme.cc\n" +
"llsapp.com\n" +
"lmjx.net\n" +
"lnk0.com\n" +
"loadingbay.com\n" +
"lofter.com\n" +
"longbridgeapp.com\n" +
"longdian.com\n" +
"lookchem.com\n" +
"lotour.com\n" +
"loupan.com\n" +
"loveinhere.com\n" +
"loveota.com\n" +
"loveota.net\n" +
"lrts.me\n" +
"lswld.com\n" +
"ltxjob.com\n" +
"luckincoffee.com\n" +
"luckincoffeecdn.com\n" +
"ludashi.com\n" +
"ludashisafe.com\n" +
"lufengzhe.com\n" +
"luojilab.com\n" +
"lvcampaign.com\n" +
"lvyouw.net\n" +
"lwjt.net\n" +
"lxcvc.com\n" +
"lxdns.com\n" +
"ly.com\n" +
"ly200-cdn.com\n" +
"ly200.com\n" +
"lynkco.com\n" +
"lywww.com\n" +
"lzyun.vip\n" +
"m5stack.com\n" +
"mabangerp.com\n" +
"madboxi.com\n" +
"made-in-china.com\n" +
"madio.net\n" +
"magicneko.com\n" +
"magictavern.com\n" +
"magtechjournal.com\n" +
"maiche.com\n" +
"maidouke.com\n" +
"maigoo.com\n" +
"maisui1.com\n" +
"maitix.com\n" +
"makeblock.com\n" +
"makepolo.com\n" +
"mambasms.com\n" +
"mangomob.net\n" +
"manhuaren.com\n" +
"manjuu.com\n" +
"manlaxy.net\n" +
"manlaxycloud.com\n" +
"manmanbuy.com\n" +
"manulife-sinochem.com\n" +
"maoyan.com\n" +
"mapbar.com\n" +
"marmot-cloud.com\n" +
"massx.com\n" +
"mathchina.com\n" +
"max-c.com\n" +
"maxesads.com\n" +
"maxhub.com\n" +
"maxhub.vip\n" +
"maxjia.com\n" +
"mayitek.com\n" +
"mbachina.com\n" +
"mbadbaedu.com\n" +
"mbalib.com\n" +
"mc-test.com\n" +
"mcc460.pub.3gppnetwork.org\n" +
"mchost.guru\n" +
"mcidc.net\n" +
"mczsok.com\n" +
"mdm.plus\n" +
"mdvdns.com\n" +
"me4399.com\n" +
"med66.com\n" +
"mediatek.com\n" +
"mediav.com\n" +
"medproad.com\n" +
"meetsocial.com\n" +
"megvii.com\n" +
"meiba.com\n" +
"meijian.com\n" +
"meimeiriji.com\n" +
"meipai.com\n" +
"meipian.me\n" +
"meiqia.com\n" +
"meiqiacloud.com\n" +
"meishanren.com\n" +
"meishesdk.com\n" +
"meitie.com\n" +
"meitu-int.com\n" +
"meitu.com\n" +
"meituan.com\n" +
"meituan.net\n" +
"meitubase.com\n" +
"meitudata.com\n" +
"meitumv.com\n" +
"meitustat.com\n" +
"meituyun.com\n" +
"meiyan.com\n" +
"meiyanstatic.com\n" +
"meiyou.com\n" +
"meizu.com\n" +
"memuplay.com\n" +
"mentamob.com\n" +
"mescroll.com\n" +
"mesonart.com\n" +
"metal.com\n" +
"mfdns.com\n" +
"mfk.com\n" +
"mgslb.com\n" +
"mgtv.com\n" +
"mhystatic.com\n" +
"mi-dun.com\n" +
"mi-fds.com\n" +
"mi-idc.com\n" +
"mi-img.com\n" +
"mi.com\n" +
"miaoshou.com\n" +
"miaoshou.net\n" +
"miaoso.com\n" +
"miaozhen.com\n" +
"microvirt.com\n" +
"microwear.com\n" +
"micstatic.com\n" +
"micyjz.com\n" +
"midasbuy.com\n" +
"midea.com\n" +
"midway.run\n" +
"mifon.com\n" +
"migames.com\n" +
"migufun.com\n" +
"miguvideo.com\n" +
"mihoyo.com\n" +
"mihuangame.com\n" +
"mihuashi.com\n" +
"miinsurtech.com\n" +
"mijia.tech\n" +
"miliantech.com\n" +
"miliao.com\n" +
"mindray.com\n" +
"mingchaoyouxi.com\n" +
"mingfuyun.com\n" +
"mingyuanfund.com\n" +
"minigame.com\n" +
"minimax.chat\n" +
"minimax.io\n" +
"minimaxi.com\n" +
"minisforum.com\n" +
"miniso.com\n" +
"miot-spec.org\n" +
"mipay.com\n" +
"mipcdn.com\n" +
"miravia.es\n" +
"missevan.com\n" +
"mitvos.com\n" +
"miui.com\n" +
"miwifi.com\n" +
"mixdesk.net\n" +
"miyoushe.com\n" +
"mlsub.net\n" +
"mlycdn.com\n" +
"mlyns.com\n" +
"mmarket.com\n" +
"mmstat.com\n" +
"mmzh.com\n" +
"mob.com\n" +
"mobike.com\n" +
"mobilelegends.com\n" +
"mobileztgame.com\n" +
"mobrtb.com\n" +
"mobsurl.com\n" +
"mobturing.com\n" +
"mobvoi.com\n" +
"moeclub.org\n" +
"moegirl.tw\n" +
"moeking.me\n" +
"moeyuuko.com\n" +
"mofunenglish.com\n" +
"mogu.com\n" +
"mogujie.com\n" +
"moji.com\n" +
"mojichina.com\n" +
"mojidict.com\n" +
"mokahr.com\n" +
"mokexapp.tv\n" +
"molbase.com\n" +
"momocdn.com\n" +
"moneydata.hk\n" +
"mongac.com\n" +
"moomoo.com\n" +
"moonshot.ai\n" +
"mop.com\n" +
"moqie.com\n" +
"moqikaka.com\n" +
"morefreegame.com\n" +
"moreless.io\n" +
"moshua.net\n" +
"motowoo.com\n" +
"mova-tech.com\n" +
"moweather.com\n" +
"moxing.net\n" +
"moyunteng.com\n" +
"moz8.com\n" +
"moziqing.com\n" +
"mrvcdn.com\n" +
"msdkpass.com\n" +
"mshxw.com\n" +
"msndvr.com\n" +
"msproduct.download.prss.microsoft.com\n" +
"msstatic.com\n" +
"mting.info\n" +
"mtnets.com\n" +
"mubu.com\n" +
"muchong.com\n" +
"mumuplayer.com\n" +
"mwcname.com\n" +
"mwemp.com\n" +
"mxbc.net\n" +
"mxhichina.com\n" +
"mxqe.com\n" +
"my-cpaas.com\n" +
"my-imcloud.com\n" +
"my3w.com\n" +
"my7v.com\n" +
"myalicdn.com\n" +
"myapp.com\n" +
"myaqsh.com\n" +
"mychery.com\n" +
"mydnspod.net\n" +
"mydrivers.com\n" +
"myhexin.com\n" +
"myhithink.com\n" +
"myhostadmin.net\n" +
"myhuaweicloud-custom.com\n" +
"myhuaweicloud.com\n" +
"myhwclouds.com\n" +
"myip.la\n" +
"myjiedian.com\n" +
"mykeeta.com\n" +
"mykeeta.net\n" +
"myoas.com\n" +
"myoas.net\n" +
"myoppo.com\n" +
"myparallelstory.com\n" +
"mypm.net\n" +
"myqcloud.com\n" +
"myshoptago.com\n" +
"mysmth.net\n" +
"mysteel.com\n" +
"mysteelcdn.com\n" +
"mytokenpocket.vip\n" +
"myubbs.com\n" +
"myxypt.com\n" +
"myzaker.com\n" +
"myzhiniu.com\n" +
"mzres.com\n" +
"n0808.com\n" +
"name321.net\n" +
"namitiyu.com\n" +
"narkii.com\n" +
"narwal.com\n" +
"narwaltech.com\n" +
"nasimobi.com\n" +
"natapp.cc\n" +
"nb591.com\n" +
"ncsyco.com\n" +
"ndcimgs.com\n" +
"ndcjl.com\n" +
"ndcpp.com\n" +
"ndcppx.com\n" +
"nease.net\n" +
"netease.com\n" +
"netease.im\n" +
"neteasegames.net\n" +
"networkbench.com\n" +
"newdu.com\n" +
"newlandnpt.com\n" +
"news-cdn.site\n" +
"news18a.com\n" +
"newsmth.net\n" +
"nexusedgeio.com\n" +
"nfnews.com\n" +
"ngabbs.com\n" +
"ngmyt.com\n" +
"nieapps.com\n" +
"niimbot.com\n" +
"ninebot.com\n" +
"nio.com\n" +
"niparts.com\n" +
"nipic.com\n" +
"niu.com\n" +
"niucache.com\n" +
"niwangwang.com\n" +
"nj-tencentclb.com\n" +
"njmapp.com\n" +
"nlark.com\n" +
"nmbxd1.com\n" +
"nongjx.com\n" +
"norglo.com\n" +
"novaicare.com\n" +
"novelfm.com\n" +
"novelfmpic.com\n" +
"novelfmstatic.com\n" +
"novelfmvod.com\n" +
"nowcoder.com\n" +
"nowmsg.com\n" +
"nowodds.com\n" +
"nowscore.com\n" +
"noxgroup.com\n" +
"npmmirror.com\n" +
"ns1011.com\n" +
"nscloudwaf.com\n" +
"ntalker.com\n" +
"ntesmail.com\n" +
"nubia.com\n" +
"num1dns.com\n" +
"nuomi.com\n" +
"nuonuo.com\n" +
"nvcam.net\n" +
"nvidia.net\n" +
"nw-host.com\n" +
"obriccloud.com\n" +
"obsbot.com\n" +
"oceancloudapi.com\n" +
"oceanengine.com\n" +
"oceanplayable.com\n" +
"oecr.com\n" +
"offcn.com\n" +
"offerstrack.net\n" +
"officecdn.microsoft.com\n" +
"ofidc.com\n" +
"ofweek.com\n" +
"oh100.com\n" +
"oicp.net\n" +
"oicp.vip\n" +
"okhimalayanzi.com\n" +
"okii.com\n" +
"oklink.com\n" +
"okmao.com\n" +
"okmart.com\n" +
"omicshare.com\n" +
"onaliyun.com\n" +
"onegg.site\n" +
"oneplus.com\n" +
"onethingpcs.com\n" +
"onewsimg.com\n" +
"onewsvod.com\n" +
"onezapp.com\n" +
"online-cmcc.net\n" +
"onlinedown.net\n" +
"ooopic.com\n" +
"open-douyin.com\n" +
"opengame0.com\n" +
"openinstall.com\n" +
"openinstall.io\n" +
"openlearning.com\n" +
"openrasp.com\n" +
"openrasp.net\n" +
"openrice.com\n" +
"opinstallinit.com\n" +
"oplay.net\n" +
"oppo.com\n" +
"oppoer.me\n" +
"oppofind.com\n" +
"oppomobile.com\n" +
"optimized-ai.com\n" +
"orangeconnex.com\n" +
"orangepi.org\n" +
"oray.com\n" +
"oray.net\n" +
"orayimg.com\n" +
"originalimg.com\n" +
"orstatic.com\n" +
"orvibo.com\n" +
"oschina.net\n" +
"oshwhub.com\n" +
"oskwai.com\n" +
"ott4china.com\n" +
"ottai.com\n" +
"ottcn.com\n" +
"ouj.com\n" +
"oulehdtv.com\n" +
"ouo7.com\n" +
"oupeng.com\n" +
"ourdvsssvip.com\n" +
"outfit7.com\n" +
"ovscdns.com\n" +
"ovscdns.net\n" +
"p5w.net\n" +
"p6sai.com\n" +
"pa18.com\n" +
"paddlewaver.com\n" +
"palm.tech\n" +
"palmpay-inc.com\n" +
"pandaremit.com\n" +
"pangolin-dsp-toutiao.com\n" +
"pangolin-sdk-toutiao-b.com\n" +
"pangolin-sdk-toutiao.com\n" +
"pangolin-sdk-toutiao1.com\n" +
"pantum.com\n" +
"papegames.com\n" +
"partnerboost.com\n" +
"patentguru.com\n" +
"paykwai.com\n" +
"pbkrs.com\n" +
"pc120.com\n" +
"pc51.com\n" +
"pcb818.com\n" +
"pcbeta.com\n" +
"pcfreetime.com\n" +
"pchome.net\n" +
"pcpop.com\n" +
"pcwatch.com\n" +
"pddcdn.com\n" +
"pddpic.com\n" +
"pddugc.com\n" +
"pdfxd.com\n" +
"peopleapp.com\n" +
"petalmail.com\n" +
"petkit.com\n" +
"petktasia.com\n" +
"pggho.com\n" +
"pglstatp-toutiao.com\n" +
"pgosglobal.com\n" +
"pgyer.com\n" +
"pic.tripcdn.com\n" +
"picovr.com\n" +
"picoxr.com\n" +
"picp.net\n" +
"pimax.com\n" +
"pinduoduo.com\n" +
"pinduoduo.net\n" +
"pingan.com\n" +
"pinggu.org\n" +
"pingpongx.com\n" +
"pinkecity.com\n" +
"pinpopt.site\n" +
"pinzhikeji.net\n" +
"pipix.com\n" +
"pkgklk.com\n" +
"pkoplink.com\n" +
"play-analytics.com\n" +
"playdeltaforce.com\n" +
"playerinfinite.com\n" +
"playgm.cc\n" +
"playorcas.com\n" +
"plusrtc.com\n" +
"poizon.com\n" +
"pokemon-unitepgame.com\n" +
"polyv.net\n" +
"pomoho.com\n" +
"popmart.com\n" +
"pphimalayanrt.com\n" +
"ppkankan01.com\n" +
"ppsimg.com\n" +
"ppt118.com\n" +
"pptv.com\n" +
"processon.com\n" +
"proximabeta.com\n" +
"psbc.com\n" +
"psnine.com\n" +
"pstatp.com\n" +
"ptfish.org\n" +
"puata.info\n" +
"pubyun.com\n" +
"pudutech.com\n" +
"pujia8.com\n" +
"pullywood.com\n" +
"pupuapi.com\n" +
"pupumall.com\n" +
"pushauction.com\n" +
"pzzc.net\n" +
"q-dazzle.com\n" +
"q1.com\n" +
"qaxanyu.com\n" +
"qaxcloudwaf.com\n" +
"qaxwzws.com\n" +
"qbb6.com\n" +
"qbox.me\n" +
"qc188.com\n" +
"qcc.com\n" +
"qcc.qualcomm.com\n" +
"qcloud.com\n" +
"qcloud.la\n" +
"qcloudcdn.com\n" +
"qcloudcjgj.com\n" +
"qcloudimg.com\n" +
"qcloudteo.com\n" +
"qcloudwzgj.com\n" +
"qcloudzygj.com\n" +
"qcplay.com\n" +
"qcy.com\n" +
"qd-metro.com\n" +
"qdjimo.com\n" +
"qeodns.com\n" +
"qg.net\n" +
"qh-cdn.com\n" +
"qh-lb.com\n" +
"qhimg.com\n" +
"qhimgs0.com\n" +
"qhimgs1.com\n" +
"qhimgs4.com\n" +
"qhmsg.com\n" +
"qhres2.com\n" +
"qhsetup.com\n" +
"qhstatic.com\n" +
"qhupdate.com\n" +
"qiandao.com\n" +
"qiandaocdn.com\n" +
"qianjiayue.com\n" +
"qianlima.com\n" +
"qianlong.com\n" +
"qianp.com\n" +
"qiantucdn.com\n" +
"qianwen.com\n" +
"qianxin.com\n" +
"qianxincdn.com\n" +
"qianxun.com\n" +
"qianyan.biz\n" +
"qianzhan.com\n" +
"qichacha.com\n" +
"qicp.vip\n" +
"qidian.com\n" +
"qiezibenpao.com\n" +
"qifeiye.com\n" +
"qihoo.com\n" +
"qihoo.net\n" +
"qihu.com\n" +
"qihuapi.com\n" +
"qihucdn.com\n" +
"qijucn.com\n" +
"qimao.com\n" +
"qingcdn.com\n" +
"qingdaonews.com\n" +
"qinglanbaseanycast.com\n" +
"qinglanbaseunicast.com\n" +
"qingting.fm\n" +
"qingtingai.net\n" +
"qiniu.com\n" +
"qiniuapi.com\n" +
"qiniucdn.com\n" +
"qiniucloud.net\n" +
"qiniucs.com\n" +
"qiniudns.com\n" +
"qiniudns.net\n" +
"qiniup.com\n" +
"qipeiren.com\n" +
"qishui.com\n" +
"qiumibao.com\n" +
"qiumiwu.com\n" +
"qixin.com\n" +
"qiyeku.com\n" +
"qiyeshangpu.com\n" +
"qiyi.com\n" +
"qiyukf.com\n" +
"qiyukf.net\n" +
"qiyutech.tech\n" +
"qizhidao.com\n" +
"qizhihaotian.com\n" +
"qjsalia.com\n" +
"qjsalib.com\n" +
"qlivecdn.com\n" +
"qlmec.com\n" +
"qm120.com\n" +
"qm989.com\n" +
"qmail.com\n" +
"qmhd87.com\n" +
"qncha.com\n" +
"qnchrome.com\n" +
"qnqcdn.net\n" +
"qnydns.com\n" +
"qoder.com\n" +
"qooic.com\n" +
"qookkagames.com\n" +
"qq.com\n" +
"qqmail.com\n" +
"qqopenapp.com\n" +
"qquanquan.com\n" +
"qqzyw.com\n" +
"qrstuvwxyzab.com\n" +
"qss-lb.com\n" +
"qtaeixd.com\n" +
"qtlcdn.com\n" +
"qtlcname.com\n" +
"qttunion.com\n" +
"qtx.com\n" +
"qualcomm.cn.cdn.cloudflare.net\n" +
"quanmama.com\n" +
"quectel.com\n" +
"queniuaa.com\n" +
"queniuak.com\n" +
"queniubg.com\n" +
"queniubh.com\n" +
"queniubl.com\n" +
"queniubm.com\n" +
"queniucf.com\n" +
"queniuck.com\n" +
"queniuco.com\n" +
"queniudns.com\n" +
"queniudns.net\n" +
"queniufm.com\n" +
"queniuhy.com\n" +
"queniuiq.com\n" +
"queniuiy.com\n" +
"queniukr.com\n" +
"queniukt.com\n" +
"queniukw.com\n" +
"queniulf.com\n" +
"queniumf.com\n" +
"queniupl.com\n" +
"queniuqe.com\n" +
"queniuqy.com\n" +
"queniurc.com\n" +
"queniusa.com\n" +
"queniuso.com\n" +
"queniusy.com\n" +
"queniusz.com\n" +
"queniutc.com\n" +
"queniuuf.com\n" +
"queniuum.com\n" +
"queniuwx.com\n" +
"queniuyk.com\n" +
"queniuzh.com\n" +
"qufenqian.vip\n" +
"quickcep.com\n" +
"quickddns.com\n" +
"qunaer.com\n" +
"qunar.com\n" +
"qunarzz.com\n" +
"qunjielong.com\n" +
"qunliao.info\n" +
"quthing.com\n" +
"qweather.com\n" +
"qweather.net\n" +
"qwen.ai\n" +
"qwenlm.ai\n" +
"qxw18.com\n" +
"qxwz.com\n" +
"qy.net\n" +
"qy6.com\n" +
"qyer.com\n" +
"qyxxpd.com\n" +
"qzkey.com\n" +
"qznovelvod.com\n" +
"qzxdianzi.com\n" +
"r.bing.com\n" +
"r302.cc\n" +
"rainbowred.com\n" +
"ranfenghd.com\n" +
"rantu.com\n" +
"rayenergytech.com\n" +
"raysync.cloud\n" +
"razerapi.com\n" +
"razersynapse.com\n" +
"razerzone.com\n" +
"rclbbs.com\n" +
"rdcv1.com\n" +
"readfree.net\n" +
"readnos.com\n" +
"readnovel.com\n" +
"realmebbs.com\n" +
"realmemobile.com\n" +
"rebatesme.com\n" +
"recovery-soft.com\n" +
"redmagic.com\n" +
"redmart.com\n" +
"rednetdns.com\n" +
"rednote.com\n" +
"rednotecdn.com\n" +
"reibootmac.com\n" +
"renfei.net\n" +
"renren.com\n" +
"renrenchaxun.com\n" +
"renrendoc.com\n" +
"reservehemu.com\n" +
"retouchpics.com\n" +
"rivergame.net\n" +
"rj.link\n" +
"rjghome.com\n" +
"rkdatabase.com\n" +
"rmbbk.com\n" +
"rnote.com\n" +
"roadlady.com\n" +
"roai.shop\n" +
"robomaster.com\n" +
"roboneo.com\n" +
"roborock.com\n" +
"rocaircraft.com\n" +
"rokid.com\n" +
"rong-edge.com\n" +
"rongcfg.com\n" +
"ronghub.com\n" +
"rongnav.com\n" +
"rongshuxia.com\n" +
"rrioo.com\n" +
"rsscc.com\n" +
"rswaf.com\n" +
"rt-thread.org\n" +
"rtbasia.com\n" +
"rtbmax.com\n" +
"rtbwave.com\n" +
"rtc-web.com\n" +
"rtc-web.io\n" +
"rtcxyz.com\n" +
"rtxapp.com\n" +
"ruanmei.com\n" +
"ruidongcloud.com\n" +
"ruijie.com\n" +
"ruijienetworks.com\n" +
"ruiwen.com\n" +
"rumt-sg.com\n" +
"rumt-zh.com\n" +
"runcobo.com\n" +
"rundefit.com\n" +
"runoob.com\n" +
"ruofeisinian.com\n" +
"ryjer.com\n" +
"saaswaf.com\n" +
"saic-gm.com\n" +
"saicmotor.com\n" +
"salesdish.com\n" +
"samsungcloudcn.com\n" +
"samsungconnectivity.com\n" +
"samsunghealthcn.com\n" +
"sandai.net\n" +
"sangfor.com\n" +
"sangforcloud.com\n" +
"sangfordns.com\n" +
"sanguosha.com\n" +
"sankuai.com\n" +
"sanyewu.com\n" +
"sat0.net\n" +
"sc518.com\n" +
"sci-hub.shop\n" +
"sci99.com\n" +
"sciengine.com\n" +
"scrmtech.com\n" +
"sczw.com\n" +
"sd-rtn.com\n" +
"sdbeta.com\n" +
"sdchina.com\n" +
"sdo.com\n" +
"sdoprofile.com\n" +
"sdx.microsoft.com\n" +
"searchpstatp.com\n" +
"sectigochina.com\n" +
"sectigochina.com.cdn.cloudflare.net\n" +
"secu100.net\n" +
"seetong.com\n" +
"seewo.com\n" +
"seeyouyima.com\n" +
"segmentfault.com\n" +
"seirobotics.net\n" +
"sekorm.com\n" +
"sellersprite.com\n" +
"sellfox.com\n" +
"semi.design\n" +
"send2boox.com\n" +
"sendcloud.net\n" +
"sendcloud.org\n" +
"seniverse.com\n" +
"senseluxury.com\n" +
"senseyun.com\n" +
"sensorsdata.com\n" +
"sensorsdatavip.com\n" +
"sequoiacap.com\n" +
"servicewechat.com\n" +
"sf-express.com\n" +
"sf-international.com\n" +
"sfacg.com\n" +
"sg-tencentclb.cloud\n" +
"sg-tencentclb.com\n" +
"sg-tencentclb.net\n" +
"sgameglobal.com\n" +
"sgmlink.com\n" +
"sgpjbg.com\n" +
"sgst.prod.dl.playstation.net\n" +
"sh-tencentclb.cloud\n" +
"sh-tencentclb.com\n" +
"sh-tencentclb.net\n" +
"sh9130.com\n" +
"shafa.com\n" +
"shanbay.com\n" +
"shanghaidisneyresort.com\n" +
"shangxueba.com\n" +
"sharpmobi.com\n" +
"shayujizhang.com\n" +
"sheca.com\n" +
"shenchai.com\n" +
"shengtiangames.com\n" +
"shenlanbao.com\n" +
"shenshiads.com\n" +
"shenzhenair.com\n" +
"shidianguji.com\n" +
"shifen.com\n" +
"shimo.im\n" +
"shining3d.com\n" +
"shipfinder.com\n" +
"shipxy.com\n" +
"shixunsuda.com\n" +
"shiyicdn.com\n" +
"shiyue.com\n" +
"shiyuegame.com\n" +
"shobserver.com\n" +
"shopeesz.com\n" +
"shoplazza.com\n" +
"shortdramaop.com\n" +
"shoudian.org\n" +
"shouqianba.com\n" +
"shouying.tv\n" +
"shovesoft.com\n" +
"showfay.com\n" +
"shuashuati.com\n" +
"shufaji.com\n" +
"shuidichou.com\n" +
"shujupie.com\n" +
"shukwai.com\n" +
"shulex-voc.com\n" +
"shunchangzhixing.com\n" +
"shuqi.com\n" +
"shuqireader.com\n" +
"shuyun.com\n" +
"shyouai.com\n" +
"shyuhuankj.com\n" +
"shziyi.com\n" +
"sichuancancer.org\n" +
"sihoo.com\n" +
"simicloud.com\n" +
"simplecreator.net\n" +
"sina.com\n" +
"sina.net\n" +
"sinaapp.com\n" +
"sinacloud.net\n" +
"sinaedge.com\n" +
"sinanet.com\n" +
"sinastorage.com\n" +
"sinasws.com\n" +
"singaporepaya.com\n" +
"singoo.cc\n" +
"sinochem.com\n" +
"sinoclick.com\n" +
"sinopec.com\n" +
"sinotrans.com\n" +
"sisensing.com\n" +
"sixents.com\n" +
"sjwyx.com\n" +
"sjxydc.com\n" +
"skypixel.com\n" +
"skysrt.com\n" +
"skywork.ai\n" +
"skyworkcdn.com\n" +
"skyworthdigitaliot.com\n" +
"sl916.com\n" +
"slatic.net\n" +
"slwh-dfh.com\n" +
"smallfighter.com\n" +
"smart.com\n" +
"smart2pay.com\n" +
"smartcloudcon.com\n" +
"smartmidea.net\n" +
"smartont.net\n" +
"smcalia.com\n" +
"smcalib.com\n" +
"smogflycloud.com\n" +
"smtcdns.com\n" +
"smtcdns.net\n" +
"smzdm.com\n" +
"snapp.ir\n" +
"snapp.site\n" +
"snapp.taxi\n" +
"snappea.com\n" +
"snapplay.com\n" +
"snappmaps.ir\n" +
"snaptube.app\n" +
"snowballtech.com\n" +
"snsfun.com\n" +
"snssdk.com\n" +
"so.com\n" +
"so123.com\n" +
"so666gslb.com\n" +
"sobot.com\n" +
"sobot.io\n" +
"soboten.com\n" +
"software.download.prss.microsoft.com\n" +
"sogo.com\n" +
"sogou-compress.com\n" +
"sogou-diskmgr.com\n" +
"sogou-kantu.com\n" +
"sogou-pdf.com\n" +
"sogou-wallpaper.com\n" +
"sogou.com\n" +
"sogoucdn.com\n" +
"sohu.com\n" +
"sohucs.com\n" +
"sojixun.com\n" +
"sojson.com\n" +
"soku.com\n" +
"solar-engine.com\n" +
"soldeazy.com\n" +
"soletower.com\n" +
"soloknight.xyz\n" +
"soolinen.com\n" +
"soso.com\n" +
"souche.com\n" +
"soufun.com\n" +
"soufunimg.com\n" +
"soupv.com\n" +
"southcn.com\n" +
"southmoney.com\n" +
"spbycdn.com\n" +
"spcdntip.com\n" +
"specialcdnstatus.com\n" +
"sportnanoapi.com\n" +
"spoto.net\n" +
"spst2.com\n" +
"srcgsre.com\n" +
"sseinfo.com\n" +
"sskoo.com\n" +
"sspai.com\n" +
"sspeeddns.com\n" +
"ssports.com\n" +
"ssrcdn.com\n" +
"stage1st.com\n" +
"starhalo.mobi\n" +
"starrails.com\n" +
"starrydyn.com\n" +
"static.tripcdn.com\n" +
"staticaa.com\n" +
"staticfile.net\n" +
"staticfile.org\n" +
"stcn.com\n" +
"stdlibrary.com\n" +
"steamchina.com\n" +
"stkouyu.com\n" +
"stockstar.com\n" +
"stonebuy.com\n" +
"storeedge.microsoft.com\n" +
"streamax.com\n" +
"strinova.com\n" +
"studyquicks.com\n" +
"stylechina.com\n" +
"suanya.com\n" +
"sufycdn.com\n" +
"sunborngame.com\n" +
"suning.com\n" +
"sunmi.com\n" +
"supcname.com\n" +
"superacme.com\n" +
"superbuy.com\n" +
"supercachenet.com\n" +
"supermapol.com\n" +
"sve.cc\n" +
"svipgulr.com\n" +
"swhysc.com\n" +
"swjoy.com\n" +
"swsm.net\n" +
"sybasebbs.com\n" +
"syiptv.com\n" +
"syyx.com\n" +
"sz3dp.com\n" +
"szbdyd.com\n" +
"szcwdz.com\n" +
"szgla.com\n" +
"szlcsc.com\n" +
"szlongyu.com\n" +
"sznews.com\n" +
"szrfdq.com\n" +
"szwego.com\n" +
"tahua.net\n" +
"tai1000.com\n" +
"talkingdata.com\n" +
"talkingdata.net\n" +
"tamaegis.com\n" +
"tancdn.com\n" +
"tanshudata.com\n" +
"tantanapp.com\n" +
"tanwan.com\n" +
"tanx.com\n" +
"tao.co\n" +
"taobao.com\n" +
"taobao.org\n" +
"taobaocdn.com\n" +
"taocdn.com\n" +
"taohuren.com\n" +
"taopiaopiao.com\n" +
"taou.com\n" +
"taozhuo.com\n" +
"tapapis.com\n" +
"tapas.net\n" +
"tapdb.net\n" +
"tapimg.com\n" +
"tapque.com\n" +
"tapsvc.com\n" +
"taptapdada.com\n" +
"tataxingqiu.com\n" +
"tatstm.com\n" +
"tbcache.com\n" +
"tcdnlive.com\n" +
"tcdnos.com\n" +
"tcl.com\n" +
"tclclouds.com\n" +
"tcljd.com\n" +
"tclking.com\n" +
"tcloudbase.com\n" +
"tcloudbaseapp.com\n" +
"tcloudfamily.com\n" +
"tctpwebank.com\n" +
"tcylgslb.com\n" +
"tdasz.com\n" +
"tdatamaster.com\n" +
"tddmp.com\n" +
"tdnsliveovs2.com\n" +
"tdnsv12.com\n" +
"tdnsv2.com\n" +
"tdnsv5.com\n" +
"tdnsv6.com\n" +
"tdnsv8.com\n" +
"tdnsx1.com\n" +
"tec73.com\n" +
"teleows.com\n" +
"temaiapi.com\n" +
"tencent-cloud.com\n" +
"tencent-cloud.net\n" +
"tencent-stock.com\n" +
"tencent.com\n" +
"tencentcdb.com\n" +
"tencentclb.com\n" +
"tencentcloud.com\n" +
"tencentcloudapi.com\n" +
"tencentcloudbase.com\n" +
"tencentcloudga.com\n" +
"tencentcloudga030.com\n" +
"tencentcs.com\n" +
"tencentdevices.com\n" +
"tencentdns.net\n" +
"tencentiotcloud.com\n" +
"tencentmusic.com\n" +
"tencentscf.com\n" +
"tencentwm.com\n" +
"tencentyun.com\n" +
"tendacn.com\n" +
"tendawifi.com\n" +
"tenorshare.com\n" +
"tenpay.com\n" +
"teo-rum.com\n" +
"teoacc.com\n" +
"terra-master.com\n" +
"tesery.com\n" +
"tfidc.net\n" +
"tfogc.com\n" +
"tfzq.com\n" +
"tgalileo.com\n" +
"th.bing.com\n" +
"thatsmags.com\n" +
"thclouds.com\n" +
"thefastcdns.com\n" +
"thefastfile.com\n" +
"thefastimg.com\n" +
"thefatherofsalmon.com\n" +
"thepoizon.ru\n" +
"thinkyeah.com\n" +
"threewater.net\n" +
"ths123.com\n" +
"ths8.com\n" +
"tiancaixing.com\n" +
"tiancity.com\n" +
"tianmu.mobi\n" +
"tianqi.com\n" +
"tianqihoubao.com\n" +
"tianqistatic.com\n" +
"tiantianfunds.com\n" +
"tianwenca.com\n" +
"tianyancha.com\n" +
"tianyucangqiongxiaoshuo.com\n" +
"ticp.net\n" +
"tidb.net\n" +
"tiebaimg.com\n" +
"tiens.com\n" +
"tigerbbs.com\n" +
"tigerfintech.com\n" +
"tiktokrow-cdn.com\n" +
"tineco.com\n" +
"tingmall.com\n" +
"tingroom.com\n" +
"tingyun.com\n" +
"tiqcdn.com\n" +
"titan007.com\n" +
"tjjt360.com\n" +
"tk.anythinktech.com\n" +
"tkww.hk\n" +
"tl88.net\n" +
"tliveapp.com\n" +
"tlivecdn.com\n" +
"tlivedns.com\n" +
"tlivemcdn.com\n" +
"tliveplay.com\n" +
"tlivepush.com\n" +
"tlivesdk.com\n" +
"tlivesdkconfig.com\n" +
"tlivesource.com\n" +
"tliveupload.com\n" +
"tmall.com\n" +
"tmall.hk\n" +
"tmctool.com\n" +
"tmtpost.com\n" +
"tnas.online\n" +
"tngdigital.com.my\n" +
"to8to.com\n" +
"tobsnssdk.com\n" +
"todesk.com\n" +
"tom.com\n" +
"tomatogames.com\n" +
"tomoremusic.com\n" +
"tongdun.net\n" +
"tongmengguo.com\n" +
"tongtool.com\n" +
"tongtut.com\n" +
"tongyi.com\n" +
"toocle.com\n" +
"tool.lu\n" +
"topcpu.net\n" +
"topgslb.com\n" +
"topmediai.com\n" +
"topwidgets.com\n" +
"totwoo.com\n" +
"touch-moblie.com\n" +
"touchngo.com.my\n" +
"tourboxtech.com\n" +
"toutiao.com\n" +
"toutiaoapi.com\n" +
"toutiaocloud.com\n" +
"toutiaocloud.net\n" +
"toutiaoimg.com\n" +
"toutiaostatic.com\n" +
"toutiaovod.com\n" +
"toutiaoyule.com\n" +
"touzime.com\n" +
"touzime.net\n" +
"tower.im\n" +
"tpadx.com\n" +
"tpstatic.net\n" +
"trackingio.com\n" +
"trackingmore.com\n" +
"trademessenger.com\n" +
"tradew.com\n" +
"tradplusad.com\n" +
"trainsimchina.com\n" +
"tranplanet.com\n" +
"transsion-os.com\n" +
"tratao.com\n" +
"trinasolar.com\n" +
"trnox.com\n" +
"trpcdn.net\n" +
"trustasia.com\n" +
"trustdecision.com\n" +
"trustexporter.com\n" +
"trustie.net\n" +
"tsxcfw.com\n" +
"tsyexmail.com\n" +
"ttalkai.com\n" +
"ttdnsa.com\n" +
"ttgtm.com\n" +
"ttic.cc\n" +
"ttlock.com\n" +
"ttwebview.com\n" +
"ttwifi.net\n" +
"tuchong.com\n" +
"tudou.com\n" +
"tuhu.org\n" +
"tuiguangjia.com\n" +
"tujia.com\n" +
"tukuppt.com\n" +
"tuliu.com\n" +
"tuniu.com\n" +
"tuozhe8.com\n" +
"turingfraud.net\n" +
"tushuokeji.net\n" +
"tusij.com\n" +
"tuya.com\n" +
"tuyacn.com\n" +
"tuyoo.com\n" +
"tventry.com\n" +
"tvmao.com\n" +
"tvzhe.com\n" +
"tx163.com\n" +
"txcdns.com\n" +
"txfund.com\n" +
"txitech.com\n" +
"txlivecdn.com\n" +
"txtduo.com\n" +
"txzing.com\n" +
"ty-xxl.com\n" +
"ty3w.net\n" +
"tydevice.com\n" +
"tyxcdn.com\n" +
"tz1288.com\n" +
"tzgamepkg.com\n" +
"ubeethiesemo.com\n" +
"ubixioe.com\n" +
"ubnt.com\n" +
"ubtrobot.com\n" +
"uc123.com\n" +
"ucfly.com\n" +
"ucloudgda.com\n" +
"ucloudnaming.info\n" +
"ucnaming.com\n" +
"ucnaming.net\n" +
"ucweb.com\n" +
"udache.com\n" +
"udeskglobal.com\n" +
"uewaf.com\n" +
"ufileos.com\n" +
"ufyct.com\n" +
"ug.link\n" +
"ugdtimg.com\n" +
"ugnas.com\n" +
"ugslb.net\n" +
"ugsnx.com\n" +
"uhabo.com\n" +
"uhomes.com\n" +
"uisdc.com\n" +
"ulikecam.com\n" +
"ulpay.com\n" +
"umeng.com\n" +
"umengcloud.com\n" +
"umetrip.com\n" +
"umiwi.com\n" +
"umsns.com\n" +
"unaming.net\n" +
"uni-ubi.com\n" +
"unicompayment.com\n" +
"unifycarbon.com\n" +
"unihertz.com\n" +
"unionpay.com\n" +
"unionpayintl.com\n" +
"unisoc.com\n" +
"unitree.com\n" +
"uniview.com\n" +
"uodoo.com\n" +
"upaiyun.com\n" +
"upd.kaspersky.com\n" +
"updf.com\n" +
"updownstream.xyz\n" +
"updrv.com\n" +
"upqzfile.com\n" +
"ups.ksmobile.net\n" +
"upseller.com\n" +
"upst86.com\n" +
"upupview.com\n" +
"urovo.com\n" +
"use-tencentclb.cloud\n" +
"use-tencentclb.com\n" +
"use-tencentclb.net\n" +
"usitrip.com\n" +
"usw-tencentclb.cloud\n" +
"usw-tencentclb.com\n" +
"usw-tencentclb.net\n" +
"utsource.net\n" +
"uuhimalayanqm.com\n" +
"uuzuonline.net\n" +
"uwn.com\n" +
"uyun-cdn.com\n" +
"uyunad.com\n" +
"uyuncdn.com\n" +
"uyuncdn.net\n" +
"v-mate.mobi\n" +
"v15cdn.com\n" +
"v3mh.com\n" +
"v5waf.com\n" +
"v6lvs.com\n" +
"vanke.com\n" +
"variflight.com\n" +
"vasdgame.com\n" +
"vconew.com\n" +
"vconew3.com\n" +
"vdncache.com\n" +
"vedcdnlb.com\n" +
"vedsalb.com\n" +
"veer.com\n" +
"vegalb.com\n" +
"vegslb.com\n" +
"vemarsdev.com\n" +
"vemic.com\n" +
"ventoy.net\n" +
"vertciot.com\n" +
"vertu.com\n" +
"vevor.net\n" +
"vgabc.com\n" +
"vgjump.com\n" +
"vglook.com\n" +
"vhall.com\n" +
"vhallyun.com\n" +
"vhostgo.com\n" +
"viayoo.com\n" +
"vicp.cc\n" +
"vicp.io\n" +
"vicp.net\n" +
"videocc.net\n" +
"vidhash.net\n" +
"vidmate.net\n" +
"vidmatefilm.org\n" +
"vigtm-meeting-tencent.com\n" +
"vip.com\n" +
"vipgslb.com\n" +
"vipkidcdn.com\n" +
"vipmro.com\n" +
"vipshop.com\n" +
"vipsinaapp.com\n" +
"vipstatic.com\n" +
"visaforchina.org\n" +
"vishavideo.com\n" +
"vivaia.com\n" +
"vivo.com\n" +
"vivo.xyz\n" +
"vivoglobal.com\n" +
"vivojrkj.com\n" +
"vjshi.com\n" +
"vlabstatic.com\n" +
"vlabvod.com\n" +
"vlinkapi.com\n" +
"vmall.com\n" +
"vmallres.com\n" +
"vnnox.com\n" +
"vobao.com\n" +
"voc.ai\n" +
"vod-pro.com\n" +
"vod-qcloud.com\n" +
"vodplayvideo.com\n" +
"vodplayvideo.net\n" +
"volc-dns.com\n" +
"volc-dns.net\n" +
"volcalb.com\n" +
"volccdn.com\n" +
"volcddos.com\n" +
"volcdns.com\n" +
"volceapplog.com\n" +
"volcengine-dns.com\n" +
"volcengine.com\n" +
"volcenginealb.com\n" +
"volcengineapi.com\n" +
"volces.com\n" +
"volcfcdndvs.com\n" +
"volcfcdndvs1.com\n" +
"volcfcdndvs2.com\n" +
"volcfcdndvs3.com\n" +
"volcgslb-mlt.com\n" +
"volcgslb.com\n" +
"volcgtm.com\n" +
"volcimagex.net\n" +
"volcmcdn3.com\n" +
"volcmcdnalias.com\n" +
"volcsirius.com\n" +
"volcsiriusbd.com\n" +
"volcvideo.com\n" +
"volcvod.com\n" +
"volcwaf.com\n" +
"voovlive.com\n" +
"voovmeeting.com\n" +
"vpal.com\n" +
"vqaq.com\n" +
"vsamhos.com\n" +
"vscode.download.prss.microsoft.com\n" +
"vsszan.com\n" +
"vstecs.com\n" +
"vulcan.dl.playstation.net\n" +
"vurl.link\n" +
"vvhan.com\n" +
"vvstc.com\n" +
"vvvtt.com\n" +
"vxe.com\n" +
"vzhifu.net\n" +
"vzuu.com\n" +
"waimaoniu.com\n" +
"waimaoniu.net\n" +
"wakuai.com\n" +
"wali.com\n" +
"wallstreetcn.com\n" +
"wan.com\n" +
"wandoujia.com\n" +
"wangjumeng.xin\n" +
"wangsu.com\n" +
"wangyin.com\n" +
"wangzhan31.com\n" +
"wanlitong.com\n" +
"wanmei.com\n" +
"wanwang.xin\n" +
"wanyol.com\n" +
"wanzi.com\n" +
"wasu.tv\n" +
"waterdropfilter.com\n" +
"waxrain.com\n" +
"wbrks.com\n" +
"wbxcx.net\n" +
"wcsapi.com\n" +
"wcyecs.com\n" +
"wdfangyi.com\n" +
"wdyxgames.com\n" +
"we4399.com\n" +
"weathercn.com\n" +
"weatherol.com\n" +
"weavatar.com\n" +
"webank.com\n" +
"webnovel.com\n" +
"webresource.tripcdn.com\n" +
"website.xin\n" +
"websjcdn.com\n" +
"webterren.com\n" +
"wechat.com\n" +
"wechatpay-global.com\n" +
"wecom.work\n" +
"wedoany.com\n" +
"wegamex.com.hk\n" +
"weibo.com\n" +
"weibocdn.com\n" +
"weidian.com\n" +
"weifengtang.com\n" +
"weimob.com\n" +
"weixin.com\n" +
"weixinbridge.com\n" +
"weiyun.com\n" +
"weizhangwang.com\n" +
"wejianzhan.com\n" +
"welife001.com\n" +
"wellcee.com\n" +
"wendangwang.com\n" +
"wendincdn.com\n" +
"wenjuan.com\n" +
"wenkub.com\n" +
"wenweipo.com\n" +
"wenzhangba.com\n" +
"weplayapp.com\n" +
"weplayer.cc\n" +
"weshineapp.com\n" +
"wesingapp.com\n" +
"wetab.link\n" +
"wetest.net\n" +
"wetv.vip\n" +
"wetvinfo.com\n" +
"wezhan.net\n" +
"wfits.com\n" +
"whaee.com\n" +
"whecloud.com\n" +
"whoami.akamai.net\n" +
"whongtec.com\n" +
"whyrtc.com\n" +
"whysw.org\n" +
"wicp.net\n" +
"wicp.vip\n" +
"widgetable.net\n" +
"wifi.com\n" +
"windbg.download.prss.microsoft.com\n" +
"wingon-travel.com\n" +
"wiseasy.com\n" +
"wiwide.com\n" +
"wjgslb.com\n" +
"wjx.com\n" +
"wkanx.com\n" +
"wkbrowser.com\n" +
"wlanbanlv.com\n" +
"wldmarket.com\n" +
"wlzp.vip\n" +
"wmpvp.com\n" +
"wmupd.com\n" +
"wn51.com\n" +
"woa.com\n" +
"wondercv.com\n" +
"wondershare.cc\n" +
"wondershare.com\n" +
"wondershare.com.br\n" +
"wondershare.jp\n" +
"wondershare.net\n" +
"woniu.com\n" +
"woozooo.com\n" +
"wopaiyi.com\n" +
"workbuddy.link\n" +
"wosaimg.com\n" +
"woshipm.com\n" +
"wosign.com\n" +
"wps.com\n" +
"wpscdn.com\n" +
"wpsdns.com\n" +
"wpsgo.com\n" +
"wpsmail.net\n" +
"wqop2018.com\n" +
"wqxsw.com\n" +
"ws.ksmobile.net\n" +
"wsbkwai.com\n" +
"wscdns.com\n" +
"wscloudcdn.com\n" +
"wscn.net\n" +
"wscncdn.com\n" +
"wscvdns.com\n" +
"wsdvs.com\n" +
"wsdvs.info\n" +
"wsglb0.com\n" +
"wshttpdns.com\n" +
"wskam.com\n" +
"wskwai.com\n" +
"wsssec.com\n" +
"wstx.com\n" +
"wsukwai.com\n" +
"wswebcdn.com\n" +
"wswebpic.com\n" +
"wsxcme.com\n" +
"wsy400.com\n" +
"wtobj.com\n" +
"wtxcdn.com\n" +
"wtzw.com\n" +
"wubaiyi.vip\n" +
"wuchucloud.net\n" +
"wuchuyun.com\n" +
"wujijiasu.com\n" +
"wujisite.com\n" +
"wukongtongji.com\n" +
"wuta-cam.com\n" +
"wuuxiang.com\n" +
"wuyou.net\n" +
"wwstat.com\n" +
"www.epsonconnect.com\n" +
"www.redhat.com\n" +
"www.st.com\n" +
"wxamedia.com\n" +
"wxcloudrun.com\n" +
"wxgateway.com\n" +
"wxlivecdn.com\n" +
"wyjsq.com\n" +
"wzcl.net\n" +
"wzhibo.net\n" +
"x-mol.com\n" +
"x3322.net\n" +
"x431.com\n" +
"x7game.com\n" +
"x7sy.com\n" +
"xaminim.com\n" +
"xaonline.com\n" +
"xbase.cloud\n" +
"xbext.com\n" +
"xbiao.com\n" +
"xcmg.com\n" +
"xcthings.com\n" +
"xcultur.com\n" +
"xd.com\n" +
"xdcdn.com\n" +
"xdcdn.net\n" +
"xdiarys.com\n" +
"xdmssp.com\n" +
"xdplt.com\n" +
"xdrig.com\n" +
"xdrtc.com\n" +
"xdrun.com\n" +
"xed.plus\n" +
"xeknow.com\n" +
"xescdn.com\n" +
"xf-gtm.com\n" +
"xf-yun.com\n" +
"xfinfr.com\n" +
"xflimg.com\n" +
"xgimi.com\n" +
"xhby.net\n" +
"xhgamesdk.com\n" +
"xhscdn.com\n" +
"xhscdn.net\n" +
"xhslink.com\n" +
"xiachufang.com\n" +
"xiagepian.com\n" +
"xiamenair.com\n" +
"xiami.com\n" +
"xianbao.net\n" +
"xiangmu.com\n" +
"xiangtatech.com\n" +
"xiangyujiankang.com\n" +
"xiaoaiassist.com\n" +
"xiaoba001.com\n" +
"xiaodutv.com\n" +
"xiaoe-tech.com\n" +
"xiaoeknow.com\n" +
"xiaohongshu.com\n" +
"xiaohongshu.net\n" +
"xiaoji.com\n" +
"xiaojukeji.com\n" +
"xiaomagaojian.com\n" +
"xiaomi.com\n" +
"xiaomi.net\n" +
"xiaomiev.com\n" +
"xiaomimimo.com\n" +
"xiaomimobile.com\n" +
"xiaomiwear.com\n" +
"xiaomixiaoai.com\n" +
"xiaomiyoupin.com\n" +
"xiaomy.net\n" +
"xiaopeng.com\n" +
"xiaopiu.com\n" +
"xiaoshouyi.com\n" +
"xiaotiancai.com\n" +
"xiaowazi.com\n" +
"xiaoyi.com\n" +
"xiaoyuzhoufm.com\n" +
"xiawan8.com\n" +
"xicp.net\n" +
"xiguashipin.net\n" +
"xilu.com\n" +
"ximalaya.com\n" +
"xincache.com\n" +
"xindong.com\n" +
"xinghewanglu.com\n" +
"xingxingjizhang.com\n" +
"xingyeai.com\n" +
"xinhongru.com\n" +
"xinhuanet.com\n" +
"xinhuaxmt.com\n" +
"xiniu.com\n" +
"xinnet.com\n" +
"xinqiucc.com\n" +
"xinshengku.com\n" +
"xinxifabu.net\n" +
"xionguamaqui.com\n" +
"xipu.com\n" +
"xisaiwang.com\n" +
"xitek.com\n" +
"xiumi.us\n" +
"xiuxiustatic.com\n" +
"xjishu.com\n" +
"xjtudlc.com\n" +
"xlqeai.com\n" +
"xlzyd.com\n" +
"xmcdn.com\n" +
"xmeye.net\n" +
"xmfish.com\n" +
"xml-journal.net\n" +
"xn--czru2dx3eszw3lat53b.com\n" +
"xnjxnz.com\n" +
"xny365.com\n" +
"xoyo.com\n" +
"xoyocdn.com\n" +
"xp94.com\n" +
"xpcha.com\n" +
"xqhuyu.com\n" +
"xqppt.com\n" +
"xtransfer.com\n" +
"xuanruanjian.com\n" +
"xuanzhi.com\n" +
"xudoodoo.com\n" +
"xuehai.net\n" +
"xueqiu.com\n" +
"xuesexs.com\n" +
"xunkids.com\n" +
"xunlei.com\n" +
"xunxiang.site\n" +
"xunyou.com\n" +
"xunyou.mobi\n" +
"xwinvip.com\n" +
"xwpbj.com\n" +
"xx007.com\n" +
"xxpkg.com\n" +
"xxsy.net\n" +
"xxsypro.com\n" +
"xxwolo.com\n" +
"xy.com\n" +
"xycdn.com\n" +
"xydcname.com\n" +
"xydcname.net\n" +
"xynbnb.com\n" +
"xywy.com\n" +
"xyydedge.com\n" +
"xyydnode.com\n" +
"xyzcdn.net\n" +
"y5coin.com\n" +
"y5kfpt.com\n" +
"yaduo.com\n" +
"yangjibao.com\n" +
"yangkeduo.com\n" +
"yangqianguan.com\n" +
"yangyi13.com\n" +
"yangyi19.com\n" +
"yaowan.com\n" +
"yaozh.com\n" +
"yccdn.com\n" +
"ycdongxu.com\n" +
"ycgslb.com\n" +
"ycwb.com\n" +
"yd126.com\n" +
"yddsha2.com\n" +
"ydmob.com\n" +
"ydstatic.com\n" +
"ydycdn.com\n" +
"yeah.net\n" +
"yealink.com\n" +
"yeastar.com\n" +
"yebinnet.com\n" +
"yeelight.com\n" +
"yesky.com\n" +
"yfanads.com\n" +
"yfbzb.com\n" +
"yfisher.com\n" +
"yhgfb-cn-static.com\n" +
"yiban.io\n" +
"yicai.com\n" +
"yiche.com\n" +
"yidianzixun.com\n" +
"yihubaiying.com\n" +
"yiigle.com\n" +
"yiihuu.com\n" +
"yilanvaas.com\n" +
"yili.com\n" +
"yilianmeiti.com\n" +
"yimao.net\n" +
"yimaoip.com\n" +
"yingjiesheng.com\n" +
"yingleku.com\n" +
"yingt.asia\n" +
"yingt.fun\n" +
"yingxiong.com\n" +
"yingzhongshare.com\n" +
"yinhangzhaopin.com\n" +
"yinxiang.com\n" +
"yiparts.com\n" +
"yipeng888.com\n" +
"yiqi.com\n" +
"yirujs.com\n" +
"yisou.com\n" +
"yisu.com\n" +
"yitechnology.com\n" +
"yiworld.com\n" +
"yiwugo.com\n" +
"yiyaojd.com\n" +
"yiyouliao.com\n" +
"yjbys.com\n" +
"yjs-cdn.com\n" +
"yjzf.com\n" +
"ykimg.com\n" +
"yksdks.com\n" +
"ymcart.com\n" +
"ymcart.net\n" +
"ymiot.net\n" +
"ymm56.com\n" +
"ymmobi.com\n" +
"ymuuy.com\n" +
"ynshangji.com\n" +
"yodao.net\n" +
"yodo1.com\n" +
"yodo1api.com\n" +
"yolanda.hk\n" +
"yoloogames.com\n" +
"yonyou.com\n" +
"yonyoucloud.com\n" +
"yoojia.com\n" +
"youbian.com\n" +
"youbianku.com\n" +
"youboy.com\n" +
"youdao.com\n" +
"youfanerbuy.com\n" +
"youjingnetwork.com\n" +
"youku.com\n" +
"youkupic.com\n" +
"youlesp.com\n" +
"youlishipin.com\n" +
"youme.im\n" +
"youngjoygame.com\n" +
"youngle.site\n" +
"youngle.tech\n" +
"youpin898.com\n" +
"yourongsj.com\n" +
"youxi.com\n" +
"youxi567.com\n" +
"youyantech.com\n" +
"youzan.com\n" +
"youzanyun.com\n" +
"youzibuy.com\n" +
"youzu.com\n" +
"yqb.com\n" +
"yqbimg.net\n" +
"ys7.com\n" +
"yslidc.com\n" +
"ysten.com\n" +
"yt0.cc\n" +
"yto-jsd.com\n" +
"yto.xin\n" +
"ytocargo.com\n" +
"ytoexpress.com\n" +
"ytoholding.com\n" +
"ytokj.net\n" +
"ytoluohan.net\n" +
"ytoluohan.xin\n" +
"ytpu.com\n" +
"yuaigongwu.com\n" +
"yuanfudao.com\n" +
"yuanjingss.com\n" +
"yuanlin.com\n" +
"yuanqidesk.com\n" +
"yuanshen.com\n" +
"yuanzhanapp.com\n" +
"yuegongyutu.com\n" +
"yueimg.com\n" +
"yuewen.com\n" +
"yueyouxs.com\n" +
"yueyundns.com\n" +
"yukeweb.com\n" +
"yumchina.com\n" +
"yunaq.com\n" +
"yuncdn263.com\n" +
"yundasys.com\n" +
"yunduncdn.com\n" +
"yunduncdns.com\n" +
"yunduncname.com\n" +
"yundundns.com\n" +
"yunduns.com\n" +
"yundunwaf.com\n" +
"yundunwaf1.com\n" +
"yundunwaf2.com\n" +
"yundunwaf3.com\n" +
"yundunwaf4.com\n" +
"yundunwaf5.com\n" +
"yundzh.com\n" +
"yunexpress.com\n" +
"yunjiasu-cdn.net\n" +
"yunjiasu360.com\n" +
"yunmeipai.com\n" +
"yunmengdata.com\n" +
"yunos.com\n" +
"yuntiancloud.com\n" +
"yunwuxian.net\n" +
"yunxindns.com\n" +
"yunxinfw.com\n" +
"yunxinvcloud.com\n" +
"yunxish.com\n" +
"yunzhan365.com\n" +
"yunzhijia.com\n" +
"yupoo.com\n" +
"yuque.com\n" +
"yutong.com\n" +
"yuwell.com\n" +
"yuwen360.com\n" +
"yuyin.tv\n" +
"ywdier.com\n" +
"yx-g.com\n" +
"yximgs.com\n" +
"yxixy.com\n" +
"yxlady.com\n" +
"yxt.com\n" +
"yxydns.com\n" +
"yxzq.com\n" +
"yy.com\n" +
"yyclouds.com\n" +
"yystatic.com\n" +
"yyxxgame.com\n" +
"yyzqta.com\n" +
"yyzqtb.com\n" +
"yz168.cc\n" +
"yzfchat.com\n" +
"z.ai\n" +
"z1cdn.com\n" +
"z7xz.com\n" +
"z9cdn.com\n" +
"zadervice.com\n" +
"zamcs.com\n" +
"zaodian.com\n" +
"zazhipu.com\n" +
"zbj.com\n" +
"zbjimg.com\n" +
"zbstatic5.com\n" +
"zbwdj.com\n" +
"zcidclink.com\n" +
"zdic.net\n" +
"zdmimg.com\n" +
"zdnscloud.com\n" +
"zdnscloud.info\n" +
"zdnscloud.net\n" +
"zeekrlife.com\n" +
"zego.im\n" +
"zeku.com\n" +
"zengslb.com\n" +
"zenithspace.net\n" +
"zenlesszonezero.com\n" +
"zepp.com\n" +
"zg163.net\n" +
"zgbfw.com\n" +
"zgjct.com\n" +
"zgzcw.com\n" +
"zhan.com\n" +
"zhangle.com\n" +
"zhangyue.com\n" +
"zhangyue.net\n" +
"zhangyue01.com\n" +
"zhangyue02.com\n" +
"zhangyue03.com\n" +
"zhaojiao.net\n" +
"zhaopin.com\n" +
"zhaoshang.net\n" +
"zhaoshang100.com\n" +
"zhaoshang800.com\n" +
"zhaosw.com\n" +
"zhbus.org\n" +
"zhejianglong.com\n" +
"zhenai.com\n" +
"zhentoo.com\n" +
"zhhainiao.com\n" +
"zhibo8.cc\n" +
"zhibo8.com\n" +
"zhicyun.com\n" +
"zhihu.com\n" +
"zhihuifangdong.net\n" +
"zhihuishu.com\n" +
"zhihuiya.com\n" +
"zhimg.com\n" +
"zhimi.com\n" +
"zhipin.com\n" +
"zhixunkeji.xyz\n" +
"zhiye.com\n" +
"zhiyuanyun.com\n" +
"zhizhen.com\n" +
"zhongan.com\n" +
"zhuanstatic.com\n" +
"zhuanzfx.com\n" +
"zhuanzhuan.com\n" +
"zhugeio.com\n" +
"zhuishushenqi.com\n" +
"zhuqiy.com\n" +
"zicp.vip\n" +
"zidoo.tv\n" +
"zihu.com\n" +
"zijieapi.com\n" +
"zingfront.com\n" +
"ziniao.com\n" +
"ziroom.com\n" +
"ziweifu.com\n" +
"zj123.com\n" +
"zj96596.com\n" +
"zjcdn.com\n" +
"zjgslb.com\n" +
"zjtcn.com\n" +
"zk71.com\n" +
"zkteco.com\n" +
"zkxww.com\n" +
"zlongame.com\n" +
"zlwh2026.com\n" +
"znds.com\n" +
"zongheng.com\n" +
"zoomlion.com\n" +
"zoosnet.net\n" +
"zp365.com\n" +
"zqids.com\n" +
"zsbeike.com\n" +
"zstatic.net\n" +
"zsxq.com\n" +
"zt-express.com\n" +
"ztems.com\n" +
"ztgame.com\n" +
"ztinfoga.com\n" +
"zto.com\n" +
"zuan88.com\n" +
"zuche.com\n" +
"zui.com\n" +
"zuimeitianqi.com\n" +
"zuiqiangyingyu.net\n" +
"zuiyouxi.com\n" +
"zulong.com\n" +
"zuowen.net\n" +
"zuoyebang.cc\n" +
"zuoyebang.com\n" +
"zuzuche.com\n" +
"zviewcloud.com\n" +
"zwcad.com\n" +
"zwjk.com\n" +
"zwtianshangm.com\n" +
"zxxk.com\n" +
"zybang.com\n" +
"zyue.com\n" +
"zywxgames.com\n" +
"zyzhan.com\n" +
"zzcdnx.com\n" +
"zzidc.com\n" +
"zzprotect.com\n" +
"zzstep.com\n" +
"zztfly.com\n";

/* 手动添加的海外代理域名（明确走代理，不回退直连）
 * 生成日期：2026-09-22 */
var PROXY_DOMAINS =
"google.com\n" +
"youtube.com\n" +
"www.lovart.ai\n";

/* 国内顶级域：整域直连。
 * cn 覆盖 .cn / .com.cn / .net.cn / .gov.cn / .edu.cn 等全部后缀；
 * 其余为中文顶级域（.中国 .公司 .网络）。
 * 注：.top / .wang 同为国内注册局运营，但海外站点使用较多，故不列入。 */
var CN_TLDS = ["cn", "xn--fiqs8s", "xn--55qx5d", "xn--io0a7i"];

/* 本机与局域网后缀 */
var LOCAL_SUFFIXES = [".local", ".lan", ".home", ".internal", ".localhost", ".i-xx.top"];

/* 内网网段前缀（172.16.0.0/12 逐段列出，PAC 里没有位运算） */
var PRIVATE_PREFIXES = [
    "10.", "127.", "0.", "169.254.", "192.168.",
    "172.16.", "172.17.", "172.18.", "172.19.", "172.20.",
    "172.21.", "172.22.", "172.23.", "172.24.", "172.25.",
    "172.26.", "172.27.", "172.28.", "172.29.", "172.30.", "172.31."
];

var _cnMap = null;

function _startsWith(s, p) {
    return s.length >= p.length && s.substring(0, p.length) === p;
}

function _endsWith(s, p) {
    return s.length > p.length && s.substring(s.length - p.length) === p;
}

/* 首次调用时把域名表建为哈希表，之后复用 */
function getCnMap() {
    if (_cnMap !== null) { return _cnMap; }
    var map = {};
    var list = CN_DOMAINS.split("\n");
    var i;
    for (i = 0; i < list.length; i++) {
        if (list[i] !== "") { map[list[i]] = 1; }
    }
    for (i = 0; i < CN_TLDS.length; i++) { map[CN_TLDS[i]] = 1; }
    _cnMap = map;
    return map;
}

function isIpLiteral(host) {
    var i, ch;
    for (i = 0; i < host.length; i++) {
        ch = host.charAt(i);
        if (ch !== "." && (ch < "0" || ch > "9")) { return false; }
    }
    return host.length > 0 && host.indexOf(".") > 0;
}

function isPrivateIp(host) {
    var i;
    for (i = 0; i < PRIVATE_PREFIXES.length; i++) {
        if (_startsWith(host, PRIVATE_PREFIXES[i])) { return true; }
    }
    return false;
}

function FindProxyForURL(url, host) {
    if (!host) { return FALLBACK; }
    host = host.toLowerCase();
    /* 去掉 FQDN 末尾的点，例如 baidu.com. */
    if (host.charAt(host.length - 1) === ".") { host = host.substring(0, host.length - 1); }

    /* 1) IPv6（本机 / 链路本地）直连 */
    if (host.indexOf(":") >= 0) { return "DIRECT"; }

    /* 2) 单标签主机名：localhost、nas、路由器名等 */
    if (host.indexOf(".") < 0) { return "DIRECT"; }

    /* 3) 本机与局域网后缀 */
    var i;
    for (i = 0; i < LOCAL_SUFFIXES.length; i++) {
        if (_endsWith(host, LOCAL_SUFFIXES[i])) { return "DIRECT"; }
    }

    /* 4) 纯 IP 访问：内网直连，公网 IP 同样直连
     *    （IP 直连在国内基本是路由器面板、内网服务、国内 CDN 节点，
     *      走代理反而更容易连不上；如需改为走代理，把下一行换成
     *      return isPrivateIp(host) ? "DIRECT" : FALLBACK; ） */
    if (isIpLiteral(host)) { return "DIRECT"; }

    /* 5) 国内域名直连：逐级剥离子域，命中即直连 */
    var map = getCnMap();
    var labels = host.split(".");
    for (i = 0; i < labels.length; i++) {
        if (map[labels.slice(i).join(".")] === 1) { return "DIRECT"; }
    }

    /* 6) 手动添加的海外代理域名：明确走代理，不回退直连 */
    var proxyList = PROXY_DOMAINS.split("\n");
    for (i = 0; i < proxyList.length; i++) {
        if (proxyList[i] !== "" && host === proxyList[i]) { return PROXY_RULE; }
    }

    /* 7) 其余（海外站点）走代理，代理不通则直连 */
    return FALLBACK;
}
